module attributes {arch = "gfx90a", target = "rocm", target_features = "{\"device_timers\": false, \"family\": \"rocm\", \"mfma\": true}", tessera.ir.level = "target"} {
  "tessera_rocm.func"() ({
    "tessera_rocm.mfma"() {accum = "f32", arch = "gfx90a", launch = "{\"block\": \"warpgroup\", \"grid\": \"mn_tiles\", \"kernel_id\": \"matmul\", \"measurement\": \"wall_clock_pending\"}", ordinal = 0 : i64, resource = "{\"async_copy_bytes\": 64, \"barrier_count\": 2, \"queue_depth\": 2, \"register_estimate\": 64, \"shared_memory_bytes\": 65536}", result = "C", shape = "m16n16k16", source = "tessera.matmul", target = "rocm"} : () -> ()
    "tessera_rocm.wmma_gemm"() {dtype = "f16", k = 16 : i64, launch = "{\"block\": \"warpgroup\", \"grid\": \"mn_tiles\", \"kernel_id\": \"matmul\", \"measurement\": \"wall_clock_pending\"}", m = 16 : i64, n = 16 : i64, name = "gemm", ordinal = 0 : i64, resource = "{\"async_copy_bytes\": 64, \"barrier_count\": 2, \"queue_depth\": 2, \"register_estimate\": 64, \"shared_memory_bytes\": 65536}", result = "C", source = "tessera.matmul", target = "rocm"} : () -> ()
    "tessera_rocm.async_copy"() {bytes = 16 : i64, dst_space = "lds", launch = "{\"block\": \"warpgroup\", \"grid\": \"mn_tiles\", \"kernel_id\": \"matmul\", \"measurement\": \"wall_clock_pending\"}", ordinal = 0 : i64, resource = "{\"async_copy_bytes\": 64, \"barrier_count\": 2, \"queue_depth\": 2, \"register_estimate\": 64, \"shared_memory_bytes\": 65536}", result = "C", source = "tessera.matmul", src_space = "global", target = "rocm"} : () -> ()
    "tessera_rocm.wait"() {ordinal = 0 : i64} : () -> ()
    "tessera_rocm.elementwise"() {arch = "gfx90a", launch = "{\"block\": \"256\", \"grid\": \"rows\", \"kernel_id\": \"softmax\", \"measurement\": \"wall_clock_pending\"}", ordinal = 1 : i64, resource = "{\"async_copy_bytes\": 0, \"barrier_count\": 1, \"queue_depth\": 0, \"register_estimate\": 24, \"shared_memory_bytes\": 1024}", result = "P", source = "tessera.softmax", target = "rocm"} : () -> ()
    "tessera_rocm.async_copy"() {bytes = 16 : i64, dst_space = "lds", launch = "{\"block\": \"256\", \"grid\": \"rows\", \"kernel_id\": \"softmax\", \"measurement\": \"wall_clock_pending\"}", ordinal = 1 : i64, resource = "{\"async_copy_bytes\": 0, \"barrier_count\": 1, \"queue_depth\": 0, \"register_estimate\": 24, \"shared_memory_bytes\": 1024}", result = "P", source = "tessera.softmax", src_space = "global", target = "rocm"} : () -> ()
    "tessera_rocm.wait"() {ordinal = 1 : i64} : () -> ()
  }) {sym_name = "main"} : () -> ()
}