// Auto-generated by CMake — do not edit manually.
#pragma once
#define TESSERA_CLI_VERSION_MAJOR 0
#define TESSERA_CLI_VERSION_MINOR 4
#define TESSERA_CLI_VERSION_PATCH 0
#define TESSERA_CLI_VERSION_STR   "0.4.0"
