"""Generated Apple execution inventory.

This dashboard answers a deliberately narrower question than an op-support
map: *what unit executes, by which compiler form and native runtime, and at
what proof rung?*  It keeps generic dispatch, strict value calls, and packaged
subgraphs separate so an executable Apple CPU linalg call is never confused
with broad generic ``@jit(target="apple_cpu")`` coverage.
"""
from __future__ import annotations

import csv
import io
from dataclasses import dataclass


@dataclass(frozen=True)
class AppleExecutionRow:
    target: str
    unit: str
    identity: str
    compiler_form: str
    runtime_executor: str
    placement: str
    proof: str
    scope: str
    evidence: str


_CPU_VALUE_CALLS = (
    ("cholesky", "tessera_apple_cpu_cholesky_f32", "LAPACK spotrf"),
    ("tri_solve", "tessera_apple_cpu_tri_solve_f32", "LAPACK triangular solve"),
    ("cholesky_solve", "tessera_apple_cpu_cholesky_solve_f32", "LAPACK solve"),
    ("lu", "tessera_apple_cpu_lu_f32", "LAPACK getrf"),
    ("qr", "tessera_apple_cpu_qr_f32", "LAPACK geqrf/orgqr"),
    ("svd", "tessera_apple_cpu_svd_f32", "LAPACK gesdd"),
)


def rows() -> tuple[AppleExecutionRow, ...]:
    """Return the taxonomy inventory in reader-facing execution order."""
    out = [
        AppleExecutionRow(
            "apple_cpu", "op", "matmul / gemm", "generic JIT dispatch",
            "Accelerate cblas_sgemm; BNNS for f16/bf16", "native_cpu",
            "native manifest + runtime execution", "generic @jit",
            "backend_manifest._APPLE_CPU_KERNELS",
        ),
        AppleExecutionRow(
            "apple_cpu", "op", "batched_gemm (rank-3 f32)",
            "generic JIT dispatch", "Accelerate cblas_sgemm loop", "native_cpu",
            "native manifest + runtime execution", "generic @jit",
            "backend_manifest._APPLE_CPU_KERNELS",
        ),
    ]
    out.extend(
        AppleExecutionRow(
            "apple_cpu", "op", op, "Apple Value Target-IR cpu.call", executor,
            "native_cpu", "executable value-call allowlist", "strict single call",
            "tests/unit/test_apple_value_target_ir.py",
        )
        for op, _symbol, executor in _CPU_VALUE_CALLS
    )
    out.extend((
        AppleExecutionRow(
            "apple_gpu", "op / fused region", "MPS, MPSGraph, MSL, MTL4 MPP lanes",
            "generic JIT dispatch", "Metal runtime", "native_gpu",
            "per-op proof in runtime execution matrix", "generic @jit",
            "runtime_execution_matrix.csv + apple_target_map.csv",
        ),
        AppleExecutionRow(
            "apple_gpu", "subgraph", "MPSGraph authorable single-op region",
            "package recognition + explicit authoring", "MTL4 ML pipeline encoder",
            "native_gpu", "package lifecycle and numerical tests", "AOT package; not auto launch",
            "tests/unit/test_apple_package_author.py",
        ),
        AppleExecutionRow(
            "apple_gpu", "subgraph", "matmul_softmax / matmul_softmax_matmul / rmsnorm_matmul",
            "package recognition + explicit authoring", "MTL4 ML pipeline encoder",
            "native_gpu", "package lifecycle and numerical tests", "AOT package; package_call launch gated",
            "tests/unit/test_apple_jit_emit_package.py",
        ),
        AppleExecutionRow(
            "apple_gpu", "op family", "runtime.launch reference lanes",
            "family executor", "Tessera reference implementation", "reference_cpu",
            "execute-and-compare", "explicit fallback", "runtime_execution_matrix.csv",
        ),
    ))
    return tuple(out)


def render_csv() -> str:
    stream = io.StringIO()
    writer = csv.writer(stream, lineterminator="\n")
    writer.writerow(("target", "unit", "identity", "compiler_form", "runtime_executor",
                     "placement", "proof", "scope", "evidence"))
    for row in rows():
        writer.writerow((row.target, row.unit, row.identity, row.compiler_form,
                         row.runtime_executor, row.placement, row.proof,
                         row.scope, row.evidence))
    return stream.getvalue()


def render_markdown() -> str:
    lines = [
        "<!-- AUTO-GENERATED by tessera.compiler.apple_execution_inventory — do not edit. -->",
        "# Apple execution inventory",
        "",
        "This is the status authority for **execution units**, not a broad op-support claim. "
        "It separates the generic JIT route, strict Value Target-IR calls, "
        "package-authored subgraphs, and explicit CPU-reference execution.",
        "",
        "Terminology: `native_cpu` and `native_gpu` name where work runs; "
        "`reference_cpu` is correct fallback execution; `package_call launch gated` "
        "means author/load/dispatch are proven but compiler-selected package-call launch is not.",
        "",
        "| Target | Unit | Identity | Compiler form | Runtime executor | Placement | Proof | Scope | Evidence |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for row in rows():
        lines.append("| " + " | ".join((row.target, row.unit, row.identity,
                                           row.compiler_form, row.runtime_executor,
                                           row.placement, row.proof, row.scope,
                                           row.evidence)) + " |")
    lines.append("")
    return "\n".join(lines)
