"""General fusion middle-end — public facade (B1 split).

The implementation is split into an arch-agnostic middle-end
(:mod:`tessera.compiler.fusion_core`) and the Apple MSL emitter + runtime
(:mod:`tessera.compiler.emit.apple_msl`). This module re-exports both so the
historical ``from tessera.compiler.fusion import ...`` surface is unchanged.
See COMPILER_REFACTOR_PLAN Workstream B.
"""

from __future__ import annotations

from tessera.compiler.fusion_core import (
    AttentionRegion as AttentionRegion,
    AttnLoweringCost as AttnLoweringCost,
    EPILOGUE_OPS as EPILOGUE_OPS,
    EpilogueOp as EpilogueOp,
    FusedRegion as FusedRegion,
    FusionCost as FusionCost,
    GatedMatmulRegion as GatedMatmulRegion,
    MatmulRegion as MatmulRegion,
    NormChainRegion as NormChainRegion,
    POINTWISE_OPS as POINTWISE_OPS,
    PointwiseGraphRegion as PointwiseGraphRegion,
    PointwiseReduceRegion as PointwiseReduceRegion,
    REDUCTION_OPS as REDUCTION_OPS,
    ReductionOp as ReductionOp,
    SYNTH_GATED_MAX_H as SYNTH_GATED_MAX_H,
    SYNTH_MAX_D as SYNTH_MAX_D,
    SYNTH_MAX_N as SYNTH_MAX_N,
    SYNTH_MAX_N_TILED as SYNTH_MAX_N_TILED,
    _ADD_NAMES as _ADD_NAMES,
    _GATED_VERIFY_CACHE as _GATED_VERIFY_CACHE,
    _GELU_EXPR as _GELU_EXPR,
    _MATMUL_NAMES as _MATMUL_NAMES,
    _MUL_NAMES as _MUL_NAMES,
    _NORM_CHAIN_ALIASES as _NORM_CHAIN_ALIASES,
    _Op as _Op,
    _POINTWISE_ALIASES as _POINTWISE_ALIASES,
    _POINTWISE_NAMES as _POINTWISE_NAMES,
    _PW_MAX_INPUTS as _PW_MAX_INPUTS,
    _PW_REDUCE_KINDS as _PW_REDUCE_KINDS,
    _REDUCTION_ALIASES as _REDUCTION_ALIASES,
    _SCALE_NAMES as _SCALE_NAMES,
    _SOFTMAX_NAMES as _SOFTMAX_NAMES,
    _VERIFY_CACHE as _VERIFY_CACHE,
    _attn_dram_bytes as _attn_dram_bytes,
    _consumers as _consumers,
    _gelu as _gelu,
    _is_trailing_feature as _is_trailing_feature,
    _layer_norm_ref as _layer_norm_ref,
    _rmsnorm_ref as _rmsnorm_ref,
    _sigmoid_np as _sigmoid_np,
    _softmax_ref as _softmax_ref,
    _transpose_flag as _transpose_flag,
    attention_cost as attention_cost,
    attention_lowering_costs as attention_lowering_costs,
    clear_verification_cache as clear_verification_cache,
    discover_attention_regions as discover_attention_regions,
    discover_fusable_regions as discover_fusable_regions,
    discover_gated_matmul_regions as discover_gated_matmul_regions,
    discover_norm_chain_regions as discover_norm_chain_regions,
    discover_pointwise_graph as discover_pointwise_graph,
    fusion_cost as fusion_cost,
    is_pointwise_op as is_pointwise_op,
    paged_stage_bytes as paged_stage_bytes,
    select_attention_lowering as select_attention_lowering,
    should_fuse_attention as should_fuse_attention,
    should_fuse_gated as should_fuse_gated,
    should_fuse_region as should_fuse_region,
    verify_synthesized_attention as verify_synthesized_attention,
    verify_synthesized_gated as verify_synthesized_gated,
    verify_synthesized_matmul as verify_synthesized_matmul,
    verify_synthesized_pointwise as verify_synthesized_pointwise,
    verify_synthesized_region as verify_synthesized_region,
)
from tessera.compiler.emit.apple_msl import (
    AutotuneRecord as AutotuneRecord,
    SYNTH_COOPMAT_REDUCE_MAX_N as SYNTH_COOPMAT_REDUCE_MAX_N,
    SYNTH_COOPMAT_TILES as SYNTH_COOPMAT_TILES,
    SYNTH_DTYPES as SYNTH_DTYPES,
    SYNTH_VARIANTS as SYNTH_VARIANTS,
    _ATTN_ENTRY as _ATTN_ENTRY,
    _ATTN_ONLINE_ENTRY as _ATTN_ONLINE_ENTRY,
    _AUTOTUNE_CORPUS as _AUTOTUNE_CORPUS,
    _COOPMAT_REDUCE_BM as _COOPMAT_REDUCE_BM,
    _COOPMAT_REDUCTIONS as _COOPMAT_REDUCTIONS,
    _COOPMAT_TILE_CFG as _COOPMAT_TILE_CFG,
    _COOPMAT_TILE_CORPUS as _COOPMAT_TILE_CORPUS,
    _ENTRY as _ENTRY,
    _ENTRY_COOPMAT as _ENTRY_COOPMAT,
    _ENTRY_COOPMAT_REDUCE as _ENTRY_COOPMAT_REDUCE,
    _ENTRY_TILED as _ENTRY_TILED,
    _GATED_ENTRY as _GATED_ENTRY,
    _NORM_CHAIN_ENTRY as _NORM_CHAIN_ENTRY,
    _PW_ENTRY as _PW_ENTRY,
    _PW_REDUCE_ENTRY as _PW_REDUCE_ENTRY,
    _TILED_REDUCTIONS as _TILED_REDUCTIONS,
    _TILED_THREADS as _TILED_THREADS,
    _attn_dtype_tag as _attn_dtype_tag,
    _attn_f16_symbol as _attn_f16_symbol,
    _attn_symbol as _attn_symbol,
    _bf16_dtype as _bf16_dtype,
    _corpus_key as _corpus_key,
    _gated_f16_symbol as _gated_f16_symbol,
    _gated_symbol as _gated_symbol,
    _io_type as _io_type,
    _matmul_body as _matmul_body,
    _pick_best_variant as _pick_best_variant,
    _prologue_msl as _prologue_msl,
    _run_fused_region_bf16 as _run_fused_region_bf16,
    _run_fused_region_f16 as _run_fused_region_f16,
    _shape_bucket as _shape_bucket,
    _synth_coopmat_reduce_symbol as _synth_coopmat_reduce_symbol,
    _synth_coopmat_symbol as _synth_coopmat_symbol,
    _synth_f16_symbol as _synth_f16_symbol,
    _synth_norm_chain_f16_symbol as _synth_norm_chain_f16_symbol,
    _synth_norm_chain_symbol as _synth_norm_chain_symbol,
    _synth_pointwise_reduce_symbol as _synth_pointwise_reduce_symbol,
    _synth_pointwise_symbol as _synth_pointwise_symbol,
    _synth_symbol as _synth_symbol,
    _synth_tiled_symbol as _synth_tiled_symbol,
    autotune_coopmat_tile as autotune_coopmat_tile,
    autotune_enabled as autotune_enabled,
    autotune_matmul_epilogue as autotune_matmul_epilogue,
    best_variant_for as best_variant_for,
    clear_autotune_corpus as clear_autotune_corpus,
    clear_coopmat_tile_corpus as clear_coopmat_tile_corpus,
    coopmat_eligible as coopmat_eligible,
    coopmat_reduce_eligible as coopmat_reduce_eligible,
    coopmat_threads as coopmat_threads,
    coopmat_tile_for as coopmat_tile_for,
    run_fused_attention as run_fused_attention,
    run_fused_region as run_fused_region,
    run_fused_region_coopmat as run_fused_region_coopmat,
    run_fused_region_coopmat_reduce as run_fused_region_coopmat_reduce,
    run_gated_matmul_region as run_gated_matmul_region,
    run_norm_chain_region as run_norm_chain_region,
    run_pointwise_graph as run_pointwise_graph,
    run_pointwise_reduce as run_pointwise_reduce,
    select_variant as select_variant,
    synthesize_attention_msl as synthesize_attention_msl,
    synthesize_attention_online_msl as synthesize_attention_online_msl,
    synthesize_gated_matmul_msl as synthesize_gated_matmul_msl,
    synthesize_matmul_epilogue_coopmat_msl as synthesize_matmul_epilogue_coopmat_msl,
    synthesize_matmul_epilogue_msl as synthesize_matmul_epilogue_msl,
    synthesize_matmul_epilogue_msl_tiled as synthesize_matmul_epilogue_msl_tiled,
    synthesize_matmul_reduction_coopmat_msl as synthesize_matmul_reduction_coopmat_msl,
    synthesize_norm_chain_msl as synthesize_norm_chain_msl,
    synthesize_pointwise_graph_msl as synthesize_pointwise_graph_msl,
    synthesize_pointwise_reduce_msl as synthesize_pointwise_reduce_msl,
)

__all__ = [
    "EPILOGUE_OPS",
    "EpilogueOp",
    "REDUCTION_OPS",
    "ReductionOp",
    "FusedRegion",
    "AttentionRegion",
    "FusionCost",
    "fusion_cost",
    "attention_cost",
    "should_fuse_region",
    "should_fuse_attention",
    "verify_synthesized_region",
    "verify_synthesized_attention",
    "clear_verification_cache",
    "SYNTH_VARIANTS",
    "SYNTH_DTYPES",
    "SYNTH_MAX_N_TILED",
    "synthesize_matmul_epilogue_msl_tiled",
    "synthesize_matmul_epilogue_coopmat_msl",
    "run_fused_region_coopmat",
    "coopmat_eligible",
    "coopmat_tile_for",
    "coopmat_threads",
    "SYNTH_COOPMAT_TILES",
    "autotune_coopmat_tile",
    "clear_coopmat_tile_corpus",
    "synthesize_matmul_reduction_coopmat_msl",
    "run_fused_region_coopmat_reduce",
    "coopmat_reduce_eligible",
    "SYNTH_COOPMAT_REDUCE_MAX_N",
    "AutotuneRecord",
    "autotune_matmul_epilogue",
    "best_variant_for",
    "select_variant",
    "autotune_enabled",
    "autotune_matmul_epilogue",
    "clear_autotune_corpus",
    "SYNTH_MAX_N",
    "SYNTH_MAX_D",
    "synthesize_matmul_epilogue_msl",
    "synthesize_attention_msl",
    "synthesize_attention_online_msl",
    "run_fused_region",
    "run_fused_attention",
    "discover_fusable_regions",
    "discover_attention_regions",
    "GatedMatmulRegion",
    "MatmulRegion",
    "verify_synthesized_matmul",
    "synthesize_gated_matmul_msl",
    "run_gated_matmul_region",
    "should_fuse_gated",
    "verify_synthesized_gated",
    "discover_gated_matmul_regions",
    "is_pointwise_op",
]
