"""Native scaled-product program packaging and prepared HIP ownership.

The compiler outlines SSA, lowers every member through Schedule/Tile, and emits
its physical launch ABI. This module marshals that ABI; it constructs no Graph,
Tile arithmetic, kernels, intermediate device allocations or launch sequence.
"""
from __future__ import annotations
import base64
import ctypes as c
from dataclasses import dataclass
from functools import lru_cache
import json
import math
import os
import re
import shutil
import subprocess
import numpy as np
from typing import Any

def _manifest(text: str, name: str) -> dict:
    values = re.findall(r'\b' + re.escape(name) + r'\s*=\s*"([A-Za-z0-9+/=]+)"', text)
    if len(values) != 1:
        raise ValueError(f"expected exactly one native {name} manifest")
    value = json.loads(base64.b64decode(values[0], validate=True))
    if not isinstance(value, dict) or value.get("schema") != 1:
        raise ValueError("unsupported native scaled program manifest")
    return value

@dataclass(frozen=True)
class NativeScaledProgram:
    # JSON is immutable across calls. Each member includes the native program
    # witness; image hashes bind this instance to actual generated bytes.
    program_json: str
    members_json: tuple[str, ...]
    images: tuple[bytes, ...]
    graph_ir: str
    target: str

    def to_manifest(self) -> dict:
        self.validate()
        return {"schema": "tessera.native_scaled_program.v1",
                "program_json": self.program_json, "members_json": list(self.members_json),
                "images": [base64.b64encode(image).decode() for image in self.images],
                "graph_ir": self.graph_ir, "target": self.target}

    @classmethod
    def from_manifest(cls, value):
        if not isinstance(value, dict) or value.get("schema") != "tessera.native_scaled_program.v1":
            raise ValueError("native scaled package schema differs")
        # Keys contain every immutable serialized field, not dictionary identity.
        # Mutating a manifest therefore cannot reuse a previously checked ABI.
        key = (value["program_json"], tuple(value["members_json"]),
               tuple(value["images"]), value["graph_ir"], value["target"])
        if (cls is NativeScaledProgram and _binding_cache_enabled() and
                all(type(v) is str for v in (key[0], *key[1], *key[2], key[3], key[4])) and
                sum(len(v) for v in (key[0], *key[1], *key[2], key[3], key[4])) <= _BINDING_ENTRY_BYTES):
            return _cached_manifest_package(key)
        package = cls(key[0], key[1], tuple(base64.b64decode(i, validate=True) for i in key[2]),
                      key[3], key[4])
        package.validate()
        return package

    def validate(self) -> None:
        program = json.loads(self.program_json)
        steps = program["steps"]
        buffers = program["buffers"]
        arguments = program["argument_count"]
        if (self.target != "rocm_gfx1201" or program.get("schema") != 1 or
            type(arguments) is not int or not 0 < arguments <= 128 or
            not 0 < len(steps) <= 128 or len(buffers) != arguments + len(steps) or
            len(self.images) != len(steps) or len(self.members_json) != len(steps) or
            not program.get("root_ir") or not self.graph_ir):
            raise ValueError("native scaled program has inconsistent ownership")
        outputs = program["outputs"]
        kind = program.get("kind", "paired_jvp")
        roles = program.get("gradient_roles", [])
        if kind == "scale_vjp":
            if (not 5 <= arguments <= 128 or not isinstance(roles, list) or not 1 <= len(roles) < arguments or
                any(type(role) is not int or not 0 <= role < arguments - 1 for role in roles) or
                len(set(roles)) != len(roles)):
                raise ValueError("native scale gradient roles differ from the input frame")
        if (kind not in {"primal", "paired_jvp", "scale_vjp"} or
            len(outputs) != (len(roles) if kind == "scale_vjp" else 1 if kind == "primal" else 2) or
            len(set(outputs)) != len(outputs)):
            raise ValueError("native scaled output ownership differs from program kind")
        reads = [-1] * arguments + list(range(len(steps)))
        for i, (step, raw, image) in enumerate(zip(steps, self.members_json, self.images)):
            member = json.loads(raw)
            witness = json.loads(base64.b64decode(member["program_base64"], validate=True))
            if (witness != program or step["step"] != i or member["step"] != i or
                member["architecture"] != "gfx1201" or
                member["abi"] != "flattened_rank1_memref_then_i64" or
                member["inputs"] != step["inputs"] or
                member["output"] != step["output"] or step["output"] != arguments + i or
                not image.startswith(b"\x7fELF") or not member["entry"] or
                len(member["geometry"]) != 6 or
                any(type(v) is not int or v <= 0 or v > 2147483647 for v in member["geometry"]) or
                math.prod(member["geometry"][3:]) > 1024):
                raise ValueError("native scaled member ABI differs from its program")
            if step["operation"] == "tessera.scaled_matmul":
                if len(step["inputs"]) != 4 or len(member["scalars"]) != 3:
                    raise ValueError("native scaled product has an invalid scalar ABI")
            elif step["operation"] == "tessera.transpose":
                if len(step["inputs"]) != 1 or len(member["scalars"]) != 1:
                    raise ValueError("native result permutation has an invalid scalar ABI")
            elif step["operation"] == "tessera.add":
                if len(step["inputs"]) != 2 or len(member["scalars"]) != 1:
                    raise ValueError("native scaled sum has an invalid scalar ABI")
            elif step["operation"] == "tensor.generate" and kind == "scale_vjp":
                if (len(step["inputs"]) != 4 or len(member["scalars"]) != 1 or
                    step.get("gradient_role") not in {"lhs_scale", "rhs_scale"} or
                    type(step.get("gradient_argument")) is not int or
                    step["gradient_argument"] not in roles or
                    step["inputs"] != sorted(set(step["inputs"])) or
                    any(type(slot) is not int or not 0 <= slot < arguments for slot in step["inputs"]) or
                    step["inputs"][-1] != arguments - 1 or
                    step["gradient_argument"] in step["inputs"]):
                    raise ValueError("native scale reduction has an invalid captured-input ABI")
            else:
                raise ValueError("native scaled program contains an unadmitted member")
            if kind == "scale_vjp" and step["operation"] == "tessera.add":
                role = step.get("gradient_argument")
                if (type(role) is not int or role not in roles or
                    any(type(slot) is not int or not arguments <= slot < step["output"] or
                        steps[slot-arguments].get("gradient_argument") != role
                        for slot in step["inputs"])):
                    raise ValueError("native scale sum lost its gradient contribution lineage")
            for slot in step["inputs"]:
                if type(slot) is not int or not 0 <= slot < step["output"]:
                    raise ValueError("native scaled program has a non-prefix SSA input")
                reads[slot] = i
            if any(type(v) is not int or v <= 0 or v > 2**63 - 1 for v in member["scalars"]):
                raise ValueError("native scaled member scalar extent is invalid")
            output_buffer = buffers[step["output"]]
            if step["operation"] == "tessera.scaled_matmul":
                m, n, k = member["scalars"]
                lhs, rhs = (buffers[slot] for slot in step["inputs"][:2])
                batching=step.get("batching")
                if type(step.get("transposeA",False)) is not bool or (step.get("transposeA",False) and batching!="broadcast"):
                    raise ValueError("native scaled A orientation differs from its typed plane policy")
                if batching not in (None,"shared_rhs_rows","independent_rhs","shared_lhs","broadcast"):
                    raise ValueError("native scaled member batching policy differs")
                if batching=="broadcast":
                    inputs=[buffers[slot] for slot in step["inputs"]]
                    shapes=[row["shape"] for row in inputs]
                    prefix=output_buffer["shape"][:-2]
                    if any(len(shape)<2 or len(shape)-2>len(prefix) for shape in shapes):
                        raise ValueError("native independent planes have invalid prefix ranks")
                    joined=[]
                    for axis in range(len(prefix)):
                        extents=[([1]*(len(prefix)-len(shape)+2)+shape[:-2])[axis]
                                 for shape in shapes]
                        nonunit={extent for extent in extents if extent!=1}
                        if len(nonunit)>1:
                            raise ValueError("native independent planes have incompatible prefixes")
                        joined.append(next(iter(nonunit),1))
                    sa,sb=inputs[2:]
                    count=math.prod(prefix)
                    if (joined!=prefix or max(len(shape)-2 for shape in shapes)!=len(prefix) or
                        output_buffer["shape"]!=prefix+[m,n] or
                        lhs["shape"][-2:]!=([k,m] if step.get("transposeA",False) else [m,k]) or rhs["shape"][-2:] not in ([k,n],[n,k]) or
                        sa["shape"][-2]!=m or sa["shape"][-1]!=sb["shape"][-2] or
                        member["geometry"][2]!=count or
                        lhs["storage"]!="f8E4M3FN" or rhs["storage"]!="f8E4M3FN" or
                        sa["storage"]!=sb["storage"] or sa["storage"] not in ("f32","ui8","i8")):
                        raise ValueError("native independent planes differ from typed storage")
                elif batching=="shared_rhs_rows":
                    logical=lhs["shape"]
                    sa=buffers[step["inputs"][2]]
                    if (len(logical)<3 or math.prod(logical[:-1])!=m or logical[-1]!=k or
                        output_buffer["shape"]!=logical[:-1]+[n] or
                        len(sa["shape"])!=len(logical) or sa["shape"][:-1]!=logical[:-1] or
                        lhs["storage"]!="f8E4M3FN" or rhs["storage"]!="f8E4M3FN"):
                        raise ValueError("native scaled logical batch differs from physical rows")
                elif batching in ("independent_rhs","shared_lhs"):
                    batch_shape=output_buffer["shape"]
                    sa,sb=(buffers[slot] for slot in step["inputs"][2:])
                    prefix=batch_shape[:-2]
                    count=math.prod(prefix) if len(batch_shape)>=3 else 0
                    if (count<=0 or batch_shape!=prefix+[m,n] or
                        lhs["shape"]!=(prefix+[m,k] if batching=="independent_rhs" else [m,k]) or
                        rhs["shape"] not in (prefix+[k,n],prefix+[n,k]) or
                        sa["shape"][:-1]!=(prefix+[m] if batching=="independent_rhs" else [m]) or
                        sb["shape"][:-2]!=prefix or
                        member["geometry"][2]!=count or
                        lhs["storage"]!="f8E4M3FN" or rhs["storage"]!="f8E4M3FN"):
                        raise ValueError("native scaled independent batch differs from physical planes")
                elif (output_buffer["shape"] != [m,n] or lhs["shape"] not in ([m,k],[k,m])):
                    raise ValueError("native scaled runtime extents differ from typed storage")
                if output_buffer["storage"]!="f32" or (batching not in ("independent_rhs","shared_lhs","broadcast") and rhs["shape"] not in ([k,n],[n,k])):
                    raise ValueError("native scaled runtime extents differ from typed storage")
            elif step["operation"] == "tensor.generate":
                captured = [buffers[slot] for slot in step["inputs"]]
                schedule = member.get("scale_adjoint_schedule", "serial_per_scale_element")
                count = output_buffer["elements"]
                geometry = ([count,1,1,32,1,1] if schedule == "wave_per_scale_element"
                            else [(count+127)//128,1,1,128,1,1])
                if (schedule not in {"serial_per_scale_element", "wave_per_scale_element"} or
                    member["scalars"] != [count] or
                    output_buffer["storage"] != "f32" or
                    sorted(row["storage"] for row in captured) !=
                        ["f32", "f32", "f8E4M3FN", "f8E4M3FN"] or
                    member["geometry"] != geometry):
                    raise ValueError("native scale reduction storage/count/geometry differs")
            elif step["operation"] == "tessera.transpose":
                source = buffers[step["inputs"][0]]
                axes = step.get("permutation")
                rank = len(source["shape"])
                if (not isinstance(axes, list) or not 1 <= rank <= 8 or
                    len(axes) != rank or any(type(axis) is not int for axis in axes) or
                    sorted(axes) != list(range(rank)) or
                    source["storage"] != "f32" or output_buffer["storage"] != "f32" or
                    output_buffer["shape"] != [source["shape"][axis] for axis in axes] or
                    source["bytes"] != output_buffer["bytes"] or
                    member["scalars"] != [output_buffer["elements"]] or
                    member["geometry"] != [(output_buffer["elements"]-1)//256+1,1,1,256,1,1]):
                    raise ValueError("native result permutation axes/storage/count/geometry differ")
            elif (member["scalars"] != [output_buffer["elements"]] or
                  any(buffers[slot]["shape"] != output_buffer["shape"] or
                      buffers[slot]["storage"] != "f32" for slot in step["inputs"])):
                raise ValueError("native sum runtime count differs from typed storage")
        if kind == "scale_vjp":
            for role, output in zip(roles, outputs, strict=True):
                if (type(output) is not int or not arguments <= output < len(buffers) or
                    buffers[role]["storage"] != "f32" or
                    buffers[output]["shape"] != buffers[role]["shape"] or
                    steps[output-arguments].get("gradient_argument") != role):
                    raise ValueError("native gradient output differs from requested input storage")
        total = 0
        for i, buffer in enumerate(buffers):
            shape = buffer["shape"]
            count = 1
            for dim in shape:
                if type(dim) is not int or dim <= 0:
                    raise ValueError("native program storage extent is invalid")
                count *= dim
            ownership = 0 if i < arguments else 2 if i in outputs else 1
            if i in outputs:
                reads[i] = len(steps)
            if (buffer["id"] != i or buffer["elements"] != count or
                buffer["ownership"] != ownership or
                buffer["first_write"] != (-1 if i < arguments else i - arguments) or
                buffer["last_read"] != reads[i] or
                type(buffer["bytes"]) is not int or buffer["bytes"] <= 0 or
                buffer["bytes"] % count or not 1 <= buffer["bytes"] // count <= 8):
                raise ValueError("native scaled buffer lifetime/storage differs from SSA")
            total += buffer["bytes"]
        if total > 2**31 or any(type(i) is not int or not arguments <= i < len(buffers) for i in outputs):
            raise ValueError("native scaled output/capacity is invalid")

# Host-only immutable compiler-ABI binding. No device allocations/handles,
# arithmetic or launch sequence are cached here. Native preparation continues
# validating capacities, lifetimes, device/context identity and completion.
_BINDING_ENTRY_BYTES = 1024 * 1024
_BINDING_ENTRIES = 16

def _binding_cache_enabled():
    return os.environ.get("TESSERA_ROCM_PROGRAM_BINDING_CACHE", "1") == "1"

@lru_cache(maxsize=_BINDING_ENTRIES)
def _cached_manifest_package(key):
    package = NativeScaledProgram(key[0], key[1],
        tuple(base64.b64decode(i, validate=True) for i in key[2]), key[3], key[4])
    package.validate()
    return package

def _package_native_scaled(graph_ir: str, *, target: str = "rocm_gfx1201", primal: bool = False, transpose: bool = False, project_image_identity: bool = False, profile_policy: bool = False, scale_transpose_wave: bool = False, artifacts=None) -> NativeScaledProgram:
    """Package a native AD-request Graph without Python IR reconstruction."""
    if target != "rocm_gfx1201":
        raise ValueError("native scaled JVP HIP execution requires gfx1201")
    # Normalize frontend inspection spelling to registered generic MLIR syntax.
    # This changes assembly spelling only; all arithmetic is compiler-owned.
    native_source = re.sub(r'=\s+(tessera\.[A-Za-z0-9_.]+)\(', r'= "\1"(', graph_ir)
    opt = os.environ.get("TESSERA_OPT") or shutil.which("tessera-opt")
    if not opt:
        raise RuntimeError("native scaled JVP packaging requires tessera-opt")
    def compile_pipeline(pipeline, source=None):
        result = subprocess.run([opt, "--pass-pipeline=" + pipeline], input=native_source if source is None else source,
                                text=True, capture_output=True, timeout=180)
        if result.returncode:
            raise RuntimeError("native scaled JVP compiler failed: " + result.stderr)
        return result.stdout
    export = "export-scaled-transpose" if transpose else "export-scaled-primal" if primal else "export-scaled-program"
    native_pass = "tessera-autodiff-paired" if transpose else "tessera-autodiff-forward"
    exported = compile_pipeline("builtin.module(" + native_pass + "{" + export + "=true})")
    program = _manifest(exported, "tessera.autodiff.scaled_program_json")
    images, members = [], []
    from .rocm_native import _extract_hsaco
    for step in program["steps"]:
        family = ("matmul" if step["operation"] == "tessera.scaled_matmul" else
                  "reduction" if step["operation"] == "tensor.generate" else
                  "scalar_unary" if step["operation"] == "tessera.transpose" else "scalar_binary")
        index = step["step"]
        selection = "select-scaled-transpose-member" if transpose else "select-scaled-member"
        prefix = ("builtin.module(" + native_pass + "{" + export + "=true "
            f"{selection}={index}}},tessera-graph-to-schedule" +
            ("{scale-transpose-wave=true}" if scale_transpose_wave else "") + ",tessera-schedule-to-tile,")
        if project_image_identity and family == "matmul":
            target_ir = compile_pipeline(prefix +
                "tessera-rocm-executable{family=matmul input=tile output=target arch=gfx1201})")
            staging = re.findall(r'\bstaging\s*=\s*"(global|lds)"', target_ir)
            if len(staging) != 1:
                raise ValueError("native scaled member has no unique physical staging")
            lds = staging[0] == "lds"
            projection_family = "scaled_matmul_lds" if lds else "scaled_matmul"
            projected = compile_pipeline(
                "builtin.module(tessera-rocm-project-kernel-identity{family=" +
                projection_family + (" runtime-k=true" if lds else "") +
                (" primal-profile=true" if profile_policy else "") + "})", target_ir)
            binary = compile_pipeline(
                "builtin.module(tessera-rocm-executable{family=matmul input=directive output=binary arch=gfx1201})",
                projected)
            if artifacts is not None:
                artifacts.append((projected,binary))
        else:
            binary = compile_pipeline(prefix +
                f"tessera-rocm-executable{{family={family} input=tile output=binary arch=gfx1201}})")
        members.append(json.dumps(_manifest(binary, "tessera.rocm.program_member_json"), sort_keys=True))
        images.append(_extract_hsaco(binary))
    package = NativeScaledProgram(json.dumps(program, sort_keys=True), tuple(members),
                                  tuple(images), graph_ir, target)
    package.validate()
    return package

def package_native_scaled_jvp(graph_ir: str, *, target: str = "rocm_gfx1201") -> NativeScaledProgram:
    return _package_native_scaled(graph_ir, target=target)

def package_native_scaled_vjp(graph_ir: str, *, target: str = "rocm_gfx1201", schedule: str = "serial_per_scale_element") -> NativeScaledProgram:
    """Package actual native typed scale-adjoint regions; no Python arithmetic."""
    if schedule not in {"serial_per_scale_element", "wave_per_scale_element"}:
        raise ValueError("unsupported native scale transpose schedule")
    return _package_native_scaled(graph_ir, target=target, transpose=True,
        scale_transpose_wave=schedule == "wave_per_scale_element")

def package_native_scaled_primal(graph_ir: str, *, target: str = "rocm_gfx1201", project_image_identity: bool = True, profile_policy: bool = True) -> NativeScaledProgram:
    if type(project_image_identity) is not bool or type(profile_policy) is not bool:
        raise ValueError("native primal image projection must be bool")
    return _package_native_scaled(graph_ir, target=target, primal=True, project_image_identity=project_image_identity, profile_policy=profile_policy)


def package_native_scaled_primal_artifacts(graph_ir: str, *, target: str = "rocm_gfx1201"):
    """Return the actual single member image with its Target/backend receipts."""
    artifacts: list[Any] = []
    program=_package_native_scaled(graph_ir,target=target,primal=True,
        project_image_identity=True,profile_policy=True,artifacts=artifacts)
    if len(program.images)!=1 or len(artifacts)!=1:
        raise ValueError("typed primal artifact binding requires one native member")
    return program,*artifacts[0]


class _Buffer(c.Structure):
    _fields_ = [("bytes", c.c_uint64), ("elements", c.c_uint64),
                ("first_write", c.c_int64), ("last_read", c.c_int64),
                ("ownership", c.c_uint32), ("reserved", c.c_uint32)]
class _Step(c.Structure):
    _fields_ = [("image", c.c_void_p), ("image_bytes", c.c_uint64),
                ("entry", c.c_char_p), ("input_count", c.c_uint32),
                ("scalar_count", c.c_uint32), ("inputs", c.c_uint32*6),
                ("output", c.c_uint32), ("geometry", c.c_uint32*6),
                ("scalars", c.c_int64*8)]

def _status(code: int) -> None:
    if code:
        raise RuntimeError(f"native scaled HIP program status {code}")

@dataclass(frozen=True)
class _StorageSpec:
    shape: tuple[int, ...]
    storage: str
    bytes: int
    numpy_dtype: object

def _storage_numpy_dtype(storage):
    if storage == "f8E4M3FN": return np.dtype("uint8")
    if storage == "f32": return np.dtype("float32")
    if storage.startswith("ui"): return np.dtype(f"uint{storage[2:]}")
    if storage.startswith("i"): return np.dtype(f"int{storage[1:]}")
    return None

@dataclass(frozen=True)
class _BoundScaledABI:
    # Private ctypes arrays are passed to a const native ABI. Owners retain
    # the binding throughout preparation; all buffers remain owned by C++.
    buffers: object
    steps: object
    blobs: tuple
    entries: tuple
    argument_count: int
    storage: tuple[_StorageSpec, ...]
    outputs: tuple[int, ...]

def _marshal_scaled_abi(package):
    package.validate()
    program = json.loads(package.program_json)
    rows = program["buffers"]
    buffers = (_Buffer*len(rows))(*(_Buffer(b["bytes"], b["elements"], b["first_write"],
                     b["last_read"], b["ownership"], 0) for b in rows))
    blobs = tuple(c.create_string_buffer(image) for image in package.images)
    entries = tuple(json.loads(raw)["entry"].encode() for raw in package.members_json)
    steps = (_Step*len(blobs))()
    for i, (blob, raw) in enumerate(zip(blobs, package.members_json)):
        m = json.loads(raw)
        steps[i] = _Step(c.cast(blob,c.c_void_p),len(package.images[i]),entries[i],
                        len(m["inputs"]),len(m["scalars"]),
                        (c.c_uint32*6)(*m["inputs"]),m["output"],
                        (c.c_uint32*6)(*m["geometry"]),(c.c_int64*8)(*m["scalars"]))
    return _BoundScaledABI(buffers, steps, blobs, entries, program["argument_count"],
        tuple(_StorageSpec(tuple(row["shape"]),row["storage"],row["bytes"],
                           _storage_numpy_dtype(row["storage"])) for row in rows),
        tuple(program["outputs"]))

@lru_cache(maxsize=_BINDING_ENTRIES)
def _cached_scaled_abi(package):
    return _marshal_scaled_abi(package)

def _scaled_abi_binding(package):
    # Frozen package fields and their exact bytes determine the cache entry.
    size = len(package.program_json) + len(package.graph_ir)
    size += sum(map(len, package.members_json)) + sum(map(len, package.images))
    if (_binding_cache_enabled() and size <= _BINDING_ENTRY_BYTES and
            type(package.members_json) is tuple and type(package.images) is tuple):
        return _cached_scaled_abi(package)
    return _marshal_scaled_abi(package)

def pack_host_view(lib, array):
    """Materialize checked storage bytes in native C++; never tensor arithmetic."""
    from .paged_host_span import checked_host_span
    span, strides = checked_host_span(array)
    if array.flags.c_contiguous:
        return array
    if not hasattr(lib, "tessera_rocm_program_pack_host_view"):
        raise ValueError("native scaled strided storage requires the matching host pack ABI")
    pack = lib.tessera_rocm_program_pack_host_view
    pack.argtypes = [
        c.c_void_p, c.c_uint64, c.c_uint32, c.POINTER(c.c_uint64),
        c.POINTER(c.c_uint64), c.c_uint32, c.c_void_p, c.c_uint64,
    ]
    packed = np.empty(array.shape, dtype=array.dtype)
    rank = array.ndim
    _status(pack(
        c.c_void_p(array.ctypes.data), span, rank,
        (c.c_uint64 * rank)(*array.shape), (c.c_uint64 * rank)(*strides),
        array.itemsize, c.c_void_p(packed.ctypes.data), packed.nbytes,
    ))
    return packed


class PreparedScaledProgram:
    """One native owner; all member execution and private storage are in C++."""
    def __init__(self, package: NativeScaledProgram, inputs, *, runtime_library: str):
        self._binding = _scaled_abi_binding(package)
        self.package = package
        # Each owner has its own metadata snapshot; caller mutations cannot
        # corrupt the shared immutable ctypes binding or another owner.
        self._program = None
        self.lib = c.CDLL(runtime_library)
        self.handle = c.c_uint64()
        self.lib.tessera_rocm_program_prepare.argtypes = [
            c.c_char_p, c.c_uint32, c.c_uint32, c.POINTER(_Buffer), c.c_uint32,
            c.POINTER(_Step), c.POINTER(c.c_void_p), c.POINTER(c.c_uint64), c.POINTER(c.c_uint64)]
        self.lib.tessera_rocm_program_update.argtypes = [
            c.c_uint64, c.POINTER(c.c_void_p), c.POINTER(c.c_uint64)]
        self.lib.tessera_rocm_program_invoke.argtypes = [
            c.c_uint64, c.c_uint32, c.POINTER(c.c_uint64), c.POINTER(c.c_float)]
        self.lib.tessera_rocm_program_read.argtypes = [
            c.c_uint64, c.c_uint32, c.c_uint64, c.c_void_p, c.c_uint64]
        self.lib.tessera_rocm_program_close.argtypes = [c.c_uint64]
        rows = self._binding.storage
        buffers, steps = self._binding.buffers, self._binding.steps
        arrays, addresses, sizes = self._inputs(inputs)
        code = self.lib.tessera_rocm_program_prepare(
            b"gfx1201",self._binding.argument_count,len(rows),buffers,len(steps),
            steps,addresses,sizes,c.byref(self.handle))
        if code:
            if self.handle.value:
                cleanup = self.lib.tessera_rocm_program_close(self.handle)
                if cleanup:
                    raise RuntimeError(f"native preparation status {code}; retained handle {self.handle.value}, cleanup status {cleanup}")
                self.handle.value = 0
            _status(code)

    @property
    def program(self):
        # Compatibility/inspection snapshot. Execution reads only the immutable
        # checked ABI; mutating this dictionary cannot change storage contracts.
        if self._program is None:
            self._program = json.loads(self.package.program_json)
        return self._program

    def _inputs(self, inputs):
        count = self._binding.argument_count
        if len(inputs) != count:
            raise ValueError("native scaled program argument count differs")
        arrays = []
        for value, contract in zip(inputs,self._binding.storage[:count]):
            array = np.asarray(value)
            storage = contract.storage
            if storage == "f8E4M3FN" and str(array.dtype) == "float8_e4m3fn":
                array = array.view(np.uint8)
            dtype = contract.numpy_dtype
            if dtype is None or array.dtype != dtype or array.shape != contract.shape or array.nbytes != contract.bytes:
                raise ValueError("native scaled input storage/shape/layout differs")
            array = pack_host_view(self.lib, array)
            arrays.append(array)
        return arrays, (c.c_void_p*count)(*(a.ctypes.data for a in arrays)), (c.c_uint64*count)(*(a.nbytes for a in arrays))

    def update(self, inputs):
        arrays, addresses, sizes = self._inputs(inputs)
        _status(self.lib.tessera_rocm_program_update(self.handle, addresses, sizes))

    def invoke(self, *, repeats=1, timed=False):
        """Return generation and optional ms per program invocation.

        The native API averages its HIP event window over repeats; callers
        must not divide the returned elapsed value again.
        """
        if type(repeats) is not int or not 0 < repeats <= 1048576:
            raise ValueError("native repetition count is invalid")
        generation, elapsed = c.c_uint64(), c.c_float()
        _status(self.lib.tessera_rocm_program_invoke(
            self.handle,repeats,c.byref(generation),c.byref(elapsed) if timed else None))
        return generation.value, float(elapsed.value) if timed else None

    def profile_members(self, *, repeats=1024):
        """Return generation and captured device-window ms per member.

        Includes device graph dispatch; capture, instantiation and host copies
        are outside the events. This is diagnostic grouped SSA execution,
        rather than the timing of the ordinary interleaved program.
        """
        if type(repeats) is not int or not 0 < repeats <= 65536:
            raise ValueError("native member repetition count is invalid")
        profile = self.lib.tessera_rocm_program_profile_members
        profile.argtypes = [c.c_uint64, c.c_uint32, c.c_uint32,
                            c.POINTER(c.c_uint64), c.POINTER(c.c_float)]
        members = len(self._binding.steps)
        elapsed = (c.c_float * members)()
        generation = c.c_uint64()
        _status(profile(self.handle, repeats, members, c.byref(generation), elapsed))
        return generation.value, tuple(float(value) for value in elapsed)

    def read(self, generation):
        outputs = []
        for slot in self._binding.outputs:
            contract = self._binding.storage[slot]
            if contract.storage != "f32":
                raise ValueError("native paired outputs require f32 storage")
            out = np.empty(contract.shape, dtype=np.float32)
            _status(self.lib.tessera_rocm_program_read(
                self.handle,slot,generation,c.c_void_p(out.ctypes.data),out.nbytes))
            outputs.append(out)
        return tuple(outputs)

    def close(self):
        if self.handle.value:
            _status(self.lib.tessera_rocm_program_close(self.handle))
            self.handle.value = 0

    def __enter__(self): return self
    def __exit__(self,*_): self.close()
