"""Decision #29's op-level clause: does every declared ODS op have a consumer?

GOV-ODS-CONSUMER-1 (docs/audit/compiler/INTEGRATED_COMPILER_PLAN.md). Decision
#29 says a declared ODS op must be consumed by a named pass or code path, or be
deleted. This module is the scan behind `tests/unit/test_ods_op_has_consumer.py`:
it parses every op declared in the Tessera `.td` files under `src/` (archive
excluded) and classifies each one by the strongest place it is referenced.

**Parsing.** TableGen cannot be parsed by one regex, and the first version of
this gate proved it: its pattern only matched `def X : Op<Dialect, "name">`, so
the dominant form -- `def X : Dialect_Op<"name", [...]>` through a class
template -- was silently skipped (its regex matches 286 of 623 op records, measured
2026-09-27).
This parser reads `class` and `def` records with balanced `<...>` argument
lists, binds each class's template parameters, and walks the base chain until
it reaches `Op<Dialect, mnemonic, ...>`. It was cross-checked op-for-op against
`llvm-tblgen --dump-json` when it landed; `test_ods_op_has_consumer.py` pins
known ops and a synthetic `.td` so a regression in either direction fails.

**What counts as a reference.**

* ``compiler`` -- the op is named by shipped compiler code: C++ (`.cpp`/`.h`/
  `.inc`/`.td` other than its own `.td`) under `src/` or `tools/`, or Python
  under `python/tessera/`. A C++ reference is the generated class name as an
  identifier (`builder.create<FooOp>`, `OpRewritePattern<FooOp>`,
  `isa<FooOp>`, `FooOp::create(...)`), the TableGen record name (DRR
  patterns), or the full `dialect.mnemonic` (textual IR in a string). A Python
  reference is the full name inside a string literal that is not a docstring.
* ``fixture_only`` -- the op is named only by tests: lit `.mlir` fixtures,
  anything under a `test`/`tests` directory, and unit tests. **A fixture alone
  does not satisfy #29.** A fixture proves the op parses and verifies; #29
  asks for a consumer *in the compiler*, and an op that only a hand-written
  fixture ever constructs is exactly the closed-looking contract carrying
  nothing that the decision exists to catch.
* ``unreferenced`` -- nothing outside its own `.td` names it.

**What does not count.** The op's own `.td`; generated code (build trees);
comments (`//` in C++/TableGen, `#` and docstrings in Python); and the op's own
member definitions -- a column-0 line `LogicalResult FooOp::verify() {` is the
declaration's implementation, not a consumer of it. A C++ class name qualified
by a foreign namespace (`scf::YieldOp`) is not a reference to a Tessera
`YieldOp`, and a class name generated by two Tessera dialects (ODS strips the
record prefix, so `Cache_RingCreateOp` and `Tessera_RingCreateOp` both yield
`RingCreateOp`) counts only when qualified by the owning namespace. Those
rules fail closed: they can call a consumed op unconsumed, never the reverse.

**Known limit.** A name assembled at run time (`f"tessera_rocm.{kind}"`) is
invisible to any static scan; such an op reads as `fixture_only` or
`unreferenced` and its waiver must say so.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Iterable, Iterator

REPO_ROOT = Path(__file__).resolve().parents[3]

#: The shipped compiler's ODS. `examples/` and `research/` carry their own
#: dialects as demonstrations and are out of scope for the product rule.
ODS_SCOPES: tuple[str, ...] = ("src",)
#: Roots whose code is the compiler (a reference here is a consumer).
COMPILER_ROOTS: tuple[str, ...] = ("src", "tools", "python/tessera")
#: Roots whose code is tests (a reference here is a fixture).
TEST_ROOTS: tuple[str, ...] = ("tests",)

_CPP_SUFFIXES = frozenset({".cpp", ".cc", ".cxx", ".h", ".hpp", ".inc", ".mm", ".td"})
_TEXT_SUFFIXES = frozenset({".mlir", ".py"}) | _CPP_SUFFIXES
_SKIP_PARTS = frozenset({"archive", "build", "__pycache__", ".git"})
_TEST_PARTS = frozenset({"test", "tests", "unittests", "lit"})

REFERENCE_TIERS: tuple[str, ...] = ("compiler", "fixture_only", "unreferenced")


class OdsParseError(ValueError):
    """The TableGen reader met a construct it cannot resolve."""


@dataclass(frozen=True)
class OdsOp:
    """One declared op. ``full_name`` is `dialect.mnemonic`.

    ``key`` is the full name, or `full name [Record]` when two records declare
    the same name (measured 2026-09-27: `TesseraOps.td` and the unbuilt
    `tessera_neighbors.td` both declare the seven `tessera.neighbors.*` ops), so
    each record keeps its own verdict and waiver. The collision itself is gated
    by :func:`duplicate_names`.
    """

    td: Path
    record: str
    cpp_class: str
    full_name: str
    dialect_record: str
    cpp_namespace: tuple[str, ...]
    key: str = ""


# ─── TableGen reading ────────────────────────────────────────────────────────


#: A char literal, a string literal, a line comment or a block comment. Strings
#: and char literals are matched first so a `//` inside one is not a comment.
_LEXEME = re.compile(
    r"""'(?:\\.|[^'\\\n])'|"(?:\\.|[^"\\\n])*"|//[^\n]*|/\*.*?\*/""", re.S)


def strip_comments(text: str, *, blank_code_blocks: bool = False) -> str:
    """Remove `//` and `/* */` comments, keeping string and char literals.

    With ``blank_code_blocks`` TableGen `[{ ... }]` blocks are blanked first:
    for *declaration* parsing they hold descriptions and C++ snippets whose
    content is not a declaration. Reference scanning keeps them, since a
    builder in one op's `.td` may construct another op.
    """
    if blank_code_blocks:
        text = re.sub(r"\[\{.*?\}\]", lambda m: '""' + "\n" * m.group(0).count("\n"),
                      text, flags=re.S)

    def keep(m: re.Match[str]) -> str:
        tok = m.group(0)
        return tok if tok[0] in "\"'" else "\n" * tok.count("\n")

    return _LEXEME.sub(keep, text)


_OPEN = {"<": ">", "[": "]", "(": ")", "{": "}"}


def _balanced(text: str, start: int) -> int:
    """Index just past the bracket group opening at ``start``."""
    stack = [_OPEN[text[start]]]
    i = start + 1
    in_str = False
    while i < len(text):
        ch = text[i]
        if in_str:
            if ch == "\\":
                i += 2
                continue
            if ch == '"':
                in_str = False
        elif ch == '"':
            in_str = True
        elif ch in _OPEN:
            stack.append(_OPEN[ch])
        elif stack and ch == stack[-1]:
            stack.pop()
            if not stack:
                return i + 1
        i += 1
    raise OdsParseError(f"unbalanced {text[start]!r} at offset {start}")


def _split_top(text: str) -> list[str]:
    """Split on commas at bracket depth zero."""
    parts, depth, cur, in_str = [], 0, [], False
    i = 0
    while i < len(text):
        ch = text[i]
        if in_str:
            cur.append(ch)
            if ch == "\\" and i + 1 < len(text):
                cur.append(text[i + 1])
                i += 2
                continue
            if ch == '"':
                in_str = False
        elif ch == '"':
            in_str = True
            cur.append(ch)
        elif ch in "<[({":
            depth += 1
            cur.append(ch)
        elif ch in ">])}":
            depth -= 1
            cur.append(ch)
        elif ch == "," and depth == 0:
            parts.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
        i += 1
    tail = "".join(cur).strip()
    if tail:
        parts.append(tail)
    return parts


@dataclass(frozen=True)
class _Record:
    kind: str                      # "class" | "def"
    name: str
    params: tuple[tuple[str, str | None], ...]   # (name, default) for classes
    bases: tuple[tuple[str, tuple[str, ...]], ...]
    body: str


_HEAD = re.compile(r"(?<![\w$])(class|def)\s+([A-Za-z_]\w*)\s*")


def _records(text: str) -> Iterator[_Record]:
    for head in _HEAD.finditer(text):
        kind, name = head.group(1), head.group(2)
        i = head.end()
        params: list[tuple[str, str | None]] = []
        if kind == "class" and i < len(text) and text[i] == "<":
            end = _balanced(text, i)
            for p in _split_top(text[i + 1:end - 1]):
                decl, _, default = p.partition("=")
                pname = decl.split()[-1] if decl.split() else ""
                params.append((pname, default.strip() or None))
            i = end
        while i < len(text) and text[i].isspace():
            i += 1
        bases: list[tuple[str, tuple[str, ...]]] = []
        if i < len(text) and text[i] == ":":
            i += 1
            while i < len(text):
                while i < len(text) and text[i] in " \t\r\n,":
                    i += 1
                m = re.match(r"[A-Za-z_]\w*", text[i:])
                if not m:
                    break
                base = m.group(0)
                i += m.end()
                while i < len(text) and text[i].isspace():
                    i += 1
                args: tuple[str, ...] = ()
                if i < len(text) and text[i] == "<":
                    end = _balanced(text, i)
                    args = tuple(_split_top(text[i + 1:end - 1]))
                    i = end
                bases.append((base, args))
                while i < len(text) and text[i].isspace():
                    i += 1
                if i >= len(text) or text[i] != ",":
                    break
        body = ""
        while i < len(text) and text[i].isspace():
            i += 1
        if i < len(text) and text[i] == "{":
            end = _balanced(text, i)
            body = text[i + 1:end - 1]
        yield _Record(kind, name, tuple(params), tuple(bases), body)


def _unquote(value: str) -> str | None:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] == '"':
        return value[1:-1]
    return None


def _resolve_op(record: _Record, classes: dict[str, _Record]) -> tuple[str, str] | None:
    """(dialect record, mnemonic) when ``record`` derives from ``Op``, else None."""
    frontier: list[tuple[str, tuple[str, ...], dict[str, str]]] = [
        (b, a, {}) for b, a in record.bases]
    seen = 0
    while frontier:
        seen += 1
        if seen > 64:
            raise OdsParseError(f"base chain of {record.name} does not terminate")
        base, args, env = frontier.pop(0)
        args = tuple(env.get(a.strip(), a) for a in args)
        if base == "Op":
            if len(args) < 2:
                raise OdsParseError(f"{record.name}: Op<> with fewer than two arguments")
            mnemonic = _unquote(args[1])
            if mnemonic is None:
                raise OdsParseError(
                    f"{record.name}: mnemonic {args[1]!r} is not a string literal after "
                    f"binding; the reader cannot evaluate it")
            return args[0].strip(), mnemonic
        cls = classes.get(base)
        if cls is None:
            continue
        bound: dict[str, str] = {}
        for idx, (pname, default) in enumerate(cls.params):
            if idx < len(args):
                bound[pname] = args[idx]
            elif default is not None:
                bound[pname] = default
        frontier.extend((b, a, bound) for b, a in cls.bases)
    return None


def _td_files(root: Path, scopes: Iterable[str]) -> list[Path]:
    return sorted(
        p for scope in scopes for p in (root / scope).rglob("*.td")
        if not (_SKIP_PARTS & set(p.relative_to(root).parts)))


def declared_ops(root: Path = REPO_ROOT, scopes: Iterable[str] = ODS_SCOPES) -> list[OdsOp]:
    """Every op declared in the `.td` files under ``scopes``.

    Classes and dialects are read from every file first, since a class used in
    one `.td` is routinely declared in another it includes.
    """
    files = _td_files(root, scopes)
    parsed = {td: list(_records(strip_comments(td.read_text(errors="replace"),
                                               blank_code_blocks=True)))
              for td in files}
    classes: dict[str, _Record] = {}
    dialects: dict[str, tuple[str, tuple[str, ...]]] = {}
    for records in parsed.values():
        for rec in records:
            if rec.kind == "class":
                classes[rec.name] = rec
            elif any(b == "Dialect" for b, _ in rec.bases):
                name = re.search(r'let\s+name\s*=\s*"([^"]+)"', rec.body)
                ns = re.search(r'let\s+cppNamespace\s*=\s*"([^"]+)"', rec.body)
                if name:
                    dialects[rec.name] = (
                        name.group(1),
                        tuple(c for c in (ns.group(1) if ns else "").split("::") if c))
    ops: list[OdsOp] = []
    for td, records in parsed.items():
        for rec in records:
            if rec.kind != "def":
                continue
            resolved = _resolve_op(rec, classes)
            if resolved is None:
                continue
            dialect_rec, mnemonic = resolved
            if dialect_rec not in dialects:
                raise OdsParseError(
                    f"{rec.name} ({td}) names dialect record {dialect_rec!r}, which no "
                    f"scanned .td declares")
            dname, namespace = dialects[dialect_rec]
            cpp = rec.name.split("_", 1)[1] if "_" in rec.name else rec.name
            ops.append(OdsOp(td, rec.name, cpp or rec.name, f"{dname}.{mnemonic}",
                             dialect_rec, namespace))
    counts: dict[str, int] = {}
    for op in ops:
        counts[op.full_name] = counts.get(op.full_name, 0) + 1
    return [replace(op, key=op.full_name if counts[op.full_name] == 1
                    else f"{op.full_name} [{op.record}]") for op in ops]


def duplicate_names(ops: Iterable[OdsOp]) -> dict[str, list[str]]:
    """``full_name -> [records]`` for every name more than one record declares.

    Two ODS records with one textual name are a defect regardless of which is
    live: MLIR resolves `a.b.c` by its first segment, so at most one of them can
    ever be the op a parser builds, and a textual consumer cannot say which it
    meant.
    """
    owners: dict[str, list[str]] = {}
    for op in ops:
        owners.setdefault(op.full_name, []).append(op.record)
    return {name: sorted(recs) for name, recs in owners.items() if len(recs) > 1}


# ─── Reference corpus ────────────────────────────────────────────────────────

_IDENT = re.compile(r"(?<![\w:])((?:[A-Za-z_]\w*::|::)*)([A-Za-z_]\w*)")
_DOTTED = re.compile(r"(?<![\w.$%#@^!])([A-Za-z_]\w*(?:\.[A-Za-z_]\w*)+)(?![\w])")
_SELF_DEF = re.compile(r"\b([A-Za-z_]\w*)::(~?[A-Za-z_]\w*)\s*\(")
#: A C/C++ string literal, or a raw string `R"delim( ... )delim"`.
_CPP_STRING = re.compile(r'R"([^(\s]*)\((.*?)\)\1"|"((?:[^"\\\n]|\\.)*)"', re.S)


@dataclass
class _FileRefs:
    #: identifier -> set of last-qualifier components ("" = unqualified)
    idents: dict[str, set[str]]
    dotted: set[str]


def _cpp_refs(text: str) -> _FileRefs:
    text = strip_comments(text)
    idents: dict[str, set[str]] = {}
    for line in text.splitlines():
        if line and not line[0].isspace():
            # `LogicalResult FooOp::verify() {` at column 0 defines a member of
            # FooOp; it is the declaration's implementation, not a consumer.
            line = _SELF_DEF.sub(lambda m: m.group(2) + "(", line)
        for m in _IDENT.finditer(line):
            quals = [q for q in m.group(1).split("::") if q]
            idents.setdefault(m.group(2), set()).add(quals[-1] if quals else "")
    # Textual op names count only inside string literals (`"tessera.foo"`,
    # an IR skeleton in a raw string); `a.b.c` in C++ code is member access.
    dotted: set[str] = set()
    for m in _CPP_STRING.finditer(text):
        body = m.group(2) if m.group(2) is not None else m.group(3)
        dotted.update(_DOTTED.findall(body))
    return _FileRefs(idents, dotted)


def _python_strings(text: str) -> list[str]:
    """String constants that are not docstrings.

    A file that does not parse is read whole: failing to see a reference
    would turn a consumed op unconsumed, the direction a governance scan may
    err in, but a silent parse failure should not decide it either way.
    """
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return [text]
    docstrings: set[int] = set()
    strings: list[tuple[int, str]] = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            body = node.body
            if body and isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant) \
                    and isinstance(body[0].value.value, str):
                docstrings.add(id(body[0].value))
        elif isinstance(node, ast.Constant) and isinstance(node.value, str):
            strings.append((id(node), node.value))
    return [value for ident, value in strings if ident not in docstrings]


def _python_refs(text: str, names: frozenset[str] | None) -> _FileRefs:
    # Cheap prefilter: parse only a file whose raw text names a declared op.
    raw = set(_DOTTED.findall(text))
    if names is not None:
        raw &= names
    if not raw:
        return _FileRefs({}, set())
    dotted: set[str] = set()
    for s in _python_strings(text):
        dotted.update(_DOTTED.findall(s))
    return _FileRefs({}, dotted)


def _mlir_refs(text: str) -> _FileRefs:
    return _FileRefs({}, set(_DOTTED.findall(text)))


def _is_test_path(rel: Path) -> bool:
    return rel.suffix == ".mlir" or bool(_TEST_PARTS & set(rel.parts[:-1])) \
        or rel.name.startswith("test_")


@dataclass
class Corpus:
    """Per-file references, split into compiler code and tests."""

    compiler: dict[Path, _FileRefs]
    tests: dict[Path, _FileRefs]


def build_corpus(root: Path = REPO_ROOT, *, exclude: Iterable[Path] = (),
                 compiler_roots: Iterable[str] = COMPILER_ROOTS,
                 test_roots: Iterable[str] = TEST_ROOTS,
                 names: Iterable[str] | None = None) -> Corpus:
    """Scan ``root`` for references. ``names`` (the declared full names) lets
    Python files that mention none of them skip parsing; it never changes a
    result, only the cost."""
    excluded = {p.resolve() for p in exclude}
    wanted = frozenset(names) if names is not None else None
    corpus = Corpus({}, {})
    for scope in (*compiler_roots, *test_roots):
        base = root / scope
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if path.suffix not in _TEXT_SUFFIXES or not path.is_file():
                continue
            rel = path.relative_to(root)
            if _SKIP_PARTS & set(rel.parts) or path.resolve() in excluded:
                continue
            text = path.read_text(errors="replace")
            is_test = scope in test_roots or _is_test_path(rel)
            if path.suffix == ".py":
                refs = _python_refs(text, wanted)
            elif path.suffix == ".mlir":
                refs = _mlir_refs(text)
            else:
                refs = _cpp_refs(text)
            (corpus.tests if is_test or path.suffix == ".mlir" else corpus.compiler)[path] = refs
    return corpus


def _ambiguous(ops: Iterable[OdsOp]) -> set[str]:
    owners: dict[str, set[str]] = {}
    for op in ops:
        owners.setdefault(op.cpp_class, set()).add(op.full_name)
    return {cpp for cpp, names in owners.items() if len(names) > 1}


def _names_op(refs: _FileRefs, op: OdsOp, ambiguous: set[str]) -> bool:
    # A textual name two records declare cannot say which one it means; it
    # counts for both, and the collision itself is gated separately
    # (`duplicate_names`), since it is a defect whichever record is live.
    if op.record in refs.idents or op.full_name in refs.dotted:
        return True
    quals = refs.idents.get(op.cpp_class)
    if not quals:
        return False
    own = set(op.cpp_namespace)
    if op.cpp_class in ambiguous:
        # Only the owning dialect's innermost namespace disambiguates.
        return bool(op.cpp_namespace) and op.cpp_namespace[-1] in quals
    return "" in quals or bool(quals & own)


def _merge(refs: Iterable[_FileRefs]) -> _FileRefs:
    merged = _FileRefs({}, set())
    for r in refs:
        merged.dotted |= r.dotted
        for name, quals in r.idents.items():
            merged.idents.setdefault(name, set()).update(quals)
    return merged


def classify(ops: list[OdsOp], corpus: Corpus) -> dict[str, str]:
    """``op.key -> tier`` (see :data:`REFERENCE_TIERS`)."""
    ambiguous = _ambiguous(ops)
    # Merge per tier once; only the `.td` files stay per-file, since an op's
    # own `.td` must not vouch for it.
    tds = {path.resolve(): refs for path, refs in corpus.compiler.items() if path.suffix == ".td"}
    code = _merge(refs for path, refs in corpus.compiler.items() if path.suffix != ".td")
    tests = _merge(corpus.tests.values())
    tiers: dict[str, str] = {}
    for op in ops:
        own = op.td.resolve()
        if _names_op(code, op, ambiguous) or any(
                _names_op(refs, op, ambiguous) for path, refs in tds.items() if path != own):
            tier = "compiler"
        elif _names_op(tests, op, ambiguous):
            tier = "fixture_only"
        else:
            tier = "unreferenced"
        tiers[op.key] = tier
    return tiers


__all__ = [
    "COMPILER_ROOTS",
    "Corpus",
    "ODS_SCOPES",
    "OdsOp",
    "OdsParseError",
    "REFERENCE_TIERS",
    "REPO_ROOT",
    "TEST_ROOTS",
    "build_corpus",
    "classify",
    "declared_ops",
    "duplicate_names",
    "strip_comments",
]
