# CMake generated Testfile for 
# Source directory: /Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1
# Build directory: /Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[tessera_cli_smoke]=] "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/tessera_cli_unit")
set_tests_properties([=[tessera_cli_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;96;add_test;/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;0;")
add_test([=[tessera_opt_version]=] "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/bin/tessera-opt" "--version")
set_tests_properties([=[tessera_opt_version]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;97;add_test;/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;0;")
add_test([=[tessera_compile_version]=] "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/bin/tessera-compile" "--version")
set_tests_properties([=[tessera_compile_version]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;99;add_test;/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;0;")
add_test([=[tessera_compile_dry_run]=] "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/bin/tessera-compile" "data/sample.mlir" "--platform=cuda" "--arch=sm_90" "--to=ptx" "--dry-run" "--out-dir" "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/test_out/compile")
set_tests_properties([=[tessera_compile_dry_run]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;101;add_test;/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;0;")
add_test([=[tessera_opt_print_pipeline]=] "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/bin/tessera-opt" "--alias=graph-to-schedule" "--print-pipeline")
set_tests_properties([=[tessera_opt_print_pipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;105;add_test;/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;0;")
add_test([=[tessera_opt_verify_only]=] "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/bin/tessera-opt" "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/data/sample.mlir" "--verify-only")
set_tests_properties([=[tessera_opt_verify_only]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;107;add_test;/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;0;")
add_test([=[tessera_inspect_dry_run]=] "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/bin/tessera-inspect" "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/test_out/compile" "--format=json" "--dry-run")
set_tests_properties([=[tessera_inspect_dry_run]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;109;add_test;/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;0;")
add_test([=[tessera_new_dry_run]=] "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/bin/tessera-new" "my_test_proj" "--template=gemm" "--dry-run")
set_tests_properties([=[tessera_new_dry_run]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;112;add_test;/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;0;")
add_test([=[tessera_autotune_grid_dry_run]=] "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/bin/tessera-autotune" "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/data/sample.mlir" "--searcher=grid" "--trials=8" "--dry-run" "--out-dir" "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/test_out/tune")
set_tests_properties([=[tessera_autotune_grid_dry_run]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;114;add_test;/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;0;")
add_test([=[tessera_run_dry_run]=] "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/bin/tessera-run" "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/_build/test_out/compile" "--shapes=512x512x512" "--dry-run")
set_tests_properties([=[tessera_run_dry_run]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;118;add_test;/Users/gregorystoner/dev_project/tessera/tools/CLI/Tessera_CLI_Starter_v0_1/CMakeLists.txt;0;")
