"""Workstream D1 (core) — the candidate registry + accuracy-budgeted arbiter.

Decision #28's three-tier / measured-arbiter model says a kernel for a given
``(op, shape-bucket, dtype, target)`` may come from three tiers:

* **Tier 1 — synthesized** (:attr:`Tier.SYNTHESIZED`): the arch-agnostic generic
  synthesizer (region-IR → source → compile → cache → launch), e.g. the ROCm
  one-thread-per-row HIP lane / the x86 scalar-C lane.
* **Tier 2 — emitted** (:attr:`Tier.EMITTED`): a per-arch codegen plugin's tuned
  emit (PTX ``mma.sync`` / AMDGCN WMMA generated by a `Generate*` pass).
* **Tier 3 — hand-tuned** (:attr:`Tier.HAND_TUNED`): the crown-jewel shipped
  kernels (ROCm WMMA GEMM / compiled FA-2 flash-attn, NVIDIA ``wgmma``, authored
  MSL). **Lead-safety: these stay first-class candidates, displaced only when a
  compiled kernel measures both faster and in accuracy budget.**

This module is the **candidate registry** (plan D1) + a minimal **arbiter**. It is
additive: nothing routes through it until a backend registers candidates and a
caller invokes :func:`arbitrate` / :func:`run_arbitrated`. Every registered
candidate is gated by the *same* universal F4 oracle
(`fusion_core.verify_synthesized_*`) via a :class:`KernelRunner` adapter, so a
faster-but-wrong candidate is refused before it can ever be selected — the
cross-backend differential-equivalence superpower (Theory §7.5), now per
candidate rather than per backend.

**Scope boundary (what is D1 vs later):** this is the registry + F4-gate + a
selection rule. The *default* selection is **tier priority** (crown-jewel first —
lead-safe by construction) with a pluggable ``measure`` hook and a ``force``
escape hatch (plan E3). The **measured autotune loop** that replaces tier
priority with real on-device latency per shape-bucket is **D2** — deliberately
not built here; the ``measure`` parameter is the seam it drops into with no API
change. Fallback logging is **D3**.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from collections import deque
from enum import IntEnum
from typing import Any, Callable


class Tier(IntEnum):
    """Kernel provenance tier (Decision #28). Ordered so a larger value is a more
    hand-tuned / lead candidate — the default arbiter prefers the highest tier
    (lead-safety) until D2's measured loop overrides with real latency."""

    SYNTHESIZED = 1
    EMITTED = 2
    HAND_TUNED = 3


#: Canonical op-kind tags — one per ``fusion_core`` region class. A candidate
#: declares which it serves; the arbiter enumerates candidates per ``(target, op)``.
OP_FUSED_REGION = "fused_region"
OP_ATTENTION = "attention"
OP_GATED_MATMUL = "gated_matmul"
OP_POINTWISE = "pointwise"
#: A bare matmul ``D = A @ B`` (no fusion) — the op-kind for plain-GEMM candidates
#: (NVIDIA emitted mma.sync vs shipped GEMM). Keyed on ``fusion_core.MatmulRegion``.
OP_MATMUL = "matmul"

#: op-kind → (verify function name, KernelRunner method) — the seam that lets the
#: arbiter reuse the exact universal F4 oracle for each candidate.
_OP_VERIFY = {
    OP_FUSED_REGION: ("verify_synthesized_region", "run_fused_region"),
    OP_ATTENTION: ("verify_synthesized_attention", "run_fused_attention"),
    OP_GATED_MATMUL: ("verify_synthesized_gated", "run_gated_matmul_region"),
    OP_POINTWISE: ("verify_synthesized_pointwise", "run_pointwise_graph"),
    OP_MATMUL: ("verify_synthesized_matmul", "run_matmul"),
}

#: Extensible op-kinds registered by solver backends (spectral FFT, TPP stencil,
#: …).  These do not route through a ``fusion_core`` region oracle — a solver op
#: has its own numpy reference — so each supplies its own reference-diff verifier
#: ``verify_fn(candidate, region, *, atol, seed) -> bool``.  The arbiter treats
#: them exactly like the built-ins (same enumerate → F4-gate → select pipeline);
#: this is the additive seam the ``lower-*-to-target-ir`` retarget plugs into
#: without touching ``fusion_core``/``kernel_emitter``.
_OP_KIND_VERIFY: dict[str, "Callable[..., bool]"] = {}


def register_op_kind(op: str, verify_fn: "Callable[..., bool]") -> None:
    """Register a solver op-kind + its reference-diff verifier so candidates for
    ``op`` can be registered and arbitrated.  ``verify_fn(candidate, region, *,
    atol, seed)`` returns ``True`` iff the candidate ran a real kernel matching its
    numpy reference within budget.  Re-registering an ``op`` replaces its
    verifier (idempotent under module re-import)."""
    _OP_KIND_VERIFY[op] = verify_fn


def verify_by_reference(candidate: "Candidate", region: Any, inputs: "tuple",
                        reference: Any, *, atol: float) -> bool:
    """Helper for solver ``verify_fn``s: run ``candidate`` on ``inputs`` and
    compare to ``reference`` within ``atol``.  A candidate that declined to the
    numpy reference (tag in ``REFERENCE_EXECUTIONS``) does not count as a viable
    winner — same "ran a real kernel" rule the built-in gate applies (P2)."""
    import numpy as np
    from tessera.compiler.emit.kernel_emitter import REFERENCE_EXECUTIONS

    out, tag = candidate.run(region, *inputs)
    if tag in REFERENCE_EXECUTIONS:
        return False
    return bool(np.allclose(np.asarray(out), np.asarray(reference), atol=atol))


class ArbiterError(RuntimeError):
    """A forced candidate does not exist / is unavailable — names the gap so the
    caller can report rather than silently pick something else (Decision #21)."""


class Candidate(ABC):
    """One kernel candidate for an ``(op, target)`` — a single tier's way to run a
    region. The arbiter enumerates candidates, F4-gates each, and selects one.

    A candidate is narrower than a :class:`KernelRunner` (which bundles every
    op-kind for a backend): it is bound to one ``op`` and one ``tier``, so the
    same backend can register a Tier-1 synthesized lane and a Tier-3 hand-tuned
    lane for the *same* op and let the arbiter choose. :meth:`available` probes
    the device/library at call time (a hand-tuned lane may be present only on real
    silicon); :meth:`applies_to` narrows by region shape/features (the WMMA fused
    GEMM serves only bias/relu/gelu/silu epilogues, not a softmax reduction)."""

    #: Human-readable identity, unique within an ``(op, target)`` bucket — the key
    #: the ``force`` escape hatch (E3) selects by.
    name: str = ""
    #: Provenance tier — drives the default (tier-priority) selection.
    tier: Tier = Tier.SYNTHESIZED
    #: Backend id, e.g. ``"rocm"`` / ``"x86"`` / ``"nvidia"``.
    target: str = ""
    #: Which op-kind this candidate serves (one of the ``OP_*`` tags).
    op: str = OP_FUSED_REGION
    #: Precision budget vs the f32 reference (see ``KernelRunner.accuracy_atol``):
    #: a half-precision lead candidate (f16 WMMA) sets a looser value so its
    #: rounding is not misread as a miscompile. ``None`` = the oracle default.
    accuracy_atol: float | None = None

    def available(self) -> bool:
        """Whether this candidate can execute here *right now* (device/toolchain/
        library probe). Default ``True``; hand-tuned lanes override with a probe so
        they simply drop out of the enumeration off their silicon."""
        return True

    def applies_to(self, region: Any) -> bool:
        """Whether this candidate can serve ``region`` (by region type / features).
        Default ``True``; narrow in subclasses (e.g. a GEMM candidate declines a
        region with a reduction epilogue it cannot fuse)."""
        return True

    def measure_device_latency(self, region: Any, *inputs: Any, reps: int = 100,
                               warmup: int = 10) -> float | None:
        """Optional device-resident latency in milliseconds.

        Candidates with a stream/event-capable runtime override this. ``None``
        keeps them out of device-only arbitration while preserving ordinary
        end-to-end measurement.
        """
        return None

    @abstractmethod
    def run(self, region: Any, *inputs: Any, **kwargs: Any) -> tuple[Any, str]:
        """Execute ``region`` on ``inputs`` → ``(output, execution_tag)``. The tag
        follows the runner contract: a real-execution tag (``"rocm_wmma"``, …) when
        a device kernel ran, or a :data:`REFERENCE_EXECUTIONS` tag when it declined
        to the numpy reference (then the F4 oracle trusts it by construction)."""


# --- registry ----------------------------------------------------------------
_CANDIDATES: dict[tuple[str, str], list[Candidate]] = {}


def register_candidate(candidate: Candidate) -> None:
    """Register ``candidate`` under ``(target, op)``. Re-registering the same
    ``name`` in a bucket replaces it (idempotent under module re-import — the hook
    each backend uses to plug its lanes in alongside the others)."""
    if not candidate.target or not candidate.name:
        raise ValueError("Candidate.target and Candidate.name must be non-empty")
    if candidate.op not in _OP_VERIFY and candidate.op not in _OP_KIND_VERIFY:
        raise ValueError(f"unknown Candidate.op {candidate.op!r}")
    bucket = _CANDIDATES.setdefault((candidate.target, candidate.op), [])
    for i, existing in enumerate(bucket):
        if existing.name == candidate.name:
            bucket[i] = candidate
            return
    bucket.append(candidate)


def candidates_for(target: str, op: str) -> list[Candidate]:
    """All registered candidates for ``(target, op)`` (a copy; registration order)."""
    return list(_CANDIDATES.get((target, op), ()))


# --- F4-gate adapter: reuse the universal oracle per candidate ----------------
#: Namespace for a candidate probe's synthetic runner target, so its verdict lands
#: on a *candidate-private* oracle cache key — never colliding with the real
#: backend runner or a sibling candidate for the same target (PR #289 review, P1).
_PROBE_NS = "candidate"


def _as_runner(candidate: Candidate) -> Any:
    """Wrap a :class:`Candidate` as a :class:`KernelRunner` so the existing
    ``fusion_core.verify_synthesized_*`` oracle gates it unchanged — the whole
    point of D1's F4 reuse. Only the candidate's own op method is wired; the other
    three raise (the oracle never calls them for this op).

    The adapter's ``target`` is **namespaced per candidate** (``candidate::<target>
    ::<name>``): the oracle keys its verdict cache by ``runner.target``, so a shared
    ``target`` would let a Tier-3 probe's verdict be reused for the real runner or
    another candidate on the same backend. ``last_execution`` records the probe's
    execution tag so the arbiter can tell a real kernel run from a reference decline
    (a decliner provides no kernel for this region and must not win — P2)."""
    from tessera.compiler.emit.kernel_emitter import KernelRunner

    _, method = _OP_VERIFY[candidate.op]

    class _CandidateRunner(KernelRunner):
        target = f"{_PROBE_NS}::{candidate.target}::{candidate.name}"
        accuracy_atol = candidate.accuracy_atol
        last_execution: str | None = None

        def run_fused_region(self, region, *a, **k):
            return self._route("run_fused_region", region, a, k)

        def run_fused_attention(self, region, *a, **k):
            return self._route("run_fused_attention", region, a, k)

        def run_gated_matmul_region(self, region, *a, **k):
            return self._route("run_gated_matmul_region", region, a, k)

        def run_pointwise_graph(self, region, *a, **k):
            return self._route("run_pointwise_graph", region, a, k)

        def run_matmul(self, region, *a, **k):
            return self._route("run_matmul", region, a, k)

        def _route(self, called, region, a, k):
            if called != method:
                raise NotImplementedError(
                    f"candidate {candidate.name!r} serves {method}, not {called}")
            # Forward kwargs so a keyword-passed operand (e.g. residual=) reaches
            # the candidate — the oracle passes residual by keyword.
            out, tag = candidate.run(region, *a, **k)
            self.last_execution = tag
            return out, tag

    return _CandidateRunner()


def verify_candidate(candidate: Candidate, region: Any, *, atol: float = 1e-3,
                     seed: int = 0) -> bool:
    """F4-gate ``candidate`` on ``region`` **for arbitration**: ``True`` iff the
    candidate ran a *real* device kernel that matched the numpy reference within its
    ``accuracy_atol`` budget.

    This reuses the universal ``fusion_core.verify_synthesized_*`` oracle but adds
    one arbiter-specific rule: a candidate that **declined to the reference** on the
    probe returns ``False`` here. The oracle itself trusts a decline (returns
    ``True`` — "no kernel ran, nothing to distrust") for its own trust-by-
    construction path, but a decliner provides no kernel for this region; if it
    counted as verified it would win by tier and then hand back only the numpy
    reference, starving a lower tier that actually executes (PR #289 review, P2)."""
    # Solver op-kinds (spectral FFT, TPP stencil, …) supply their own
    # reference-diff verifier via register_op_kind() — they have a numpy
    # reference of their own rather than a fusion_core region oracle.
    if candidate.op in _OP_KIND_VERIFY:
        return bool(_OP_KIND_VERIFY[candidate.op](
            candidate, region, atol=atol, seed=seed))

    from tessera.compiler import fusion_core
    from tessera.compiler.emit.kernel_emitter import REFERENCE_EXECUTIONS

    verify_name, _ = _OP_VERIFY[candidate.op]
    verify = getattr(fusion_core, verify_name)
    adapter = _as_runner(candidate)
    matched = bool(verify(region, runner=adapter, force=True, atol=atol, seed=seed))
    if not matched:
        return False
    # Ran-a-real-kernel gate: a reference decline is correct-by-construction but not
    # a viable arbitration winner (see docstring).
    return adapter.last_execution not in REFERENCE_EXECUTIONS


# --- the arbiter -------------------------------------------------------------
MeasureFn = Callable[[Candidate], float]


def arbitrate(region: Any, op: str, target: str, *, verify: bool = True,
              force: str | None = None,
              measure: MeasureFn | None = None) -> Candidate | None:
    """Pick the winning candidate for ``region`` among those registered for
    ``(target, op)``, or ``None`` if none apply/verify (caller uses the reference).

    Selection pipeline: keep candidates that **apply** to the region and are
    **available** here; if ``force`` is given, restrict to that name (E3 escape
    hatch — raises :class:`ArbiterError` if it is not present/available); if
    ``verify`` (default), drop any that fail the **F4 oracle**; then choose —
    by ``measure`` (a latency callback, plan D2's seam: lowest wins) if given,
    else by **tier priority** (highest tier — crown-jewel first, lead-safe)."""
    cands = [c for c in candidates_for(target, op)
             if c.applies_to(region) and c.available()]
    if force is not None:
        forced = [c for c in cands if c.name == force]
        if not forced:
            all_names = [c.name for c in candidates_for(target, op)]
            raise ArbiterError(
                f"forced candidate {force!r} not available for ({target}, {op}); "
                f"registered: {all_names or '<none>'}")
        cands = forced
    if verify:
        cands = [c for c in cands if verify_candidate(c, region)]
    if not cands:
        return None
    if measure is not None:
        return min(cands, key=measure)
    # Default: highest tier wins (Decision #28 lead-safety) — a hand-tuned lane is
    # only displaced once D2's measured loop proves a lower tier faster + in budget.
    return max(cands, key=lambda c: (int(c.tier), -_reg_index(c)))


def _reg_index(candidate: Candidate) -> int:
    """Registration order within the bucket — a stable tie-break so equal-tier
    candidates resolve deterministically (first-registered wins)."""
    bucket = _CANDIDATES.get((candidate.target, candidate.op), [])
    for i, c in enumerate(bucket):
        if c is candidate:
            return i
    return len(bucket)


def run_arbitrated(region: Any, op: str, target: str, *inputs: Any,
                   verify: bool = True, force: str | None = None,
                   measure: MeasureFn | None = None,
                   dims: tuple[int, ...] | None = None,
                   dtype: str | None = None,
                   use_corpus: bool = True,
                   autotune_cache: Any = None,
                   device: str | None = None,
                   timing: str = "end_to_end") -> tuple[Any, str]:
    """Arbitrate then execute: pick the winning candidate and run it on
    ``inputs`` → ``(output, tag)``. When no candidate applies/verifies, fall back
    to ``region.reference(*inputs)`` tagged ``"reference"`` (Decision #21: honest —
    never a mislabeled kernel). Every dispatch is recorded in the D3 arbiter log."""
    # Explicit E3 forcing and an online measurement callback are authoritative.
    # Otherwise consult D2's persisted, device-qualified verdict before falling
    # back to tier priority. The import stays lazy to avoid candidate↔autotune's
    # module dependency becoming an import cycle.
    preferred = force
    if preferred is None and measure is None and use_corpus:
        from tessera.compiler.emit.autotune import corpus_winner
        preferred = corpus_winner(
            region, op, target, *inputs, dims=dims, dtype=dtype,
            cache=autotune_cache, device=device, timing=timing)
    winner = arbitrate(region, op, target, verify=verify, force=preferred,
                       measure=measure)
    if winner is None:
        _note_arbiter_dispatch(target, op, None, "reference")
        return region.reference(*inputs), "reference"
    out, tag = winner.run(region, *inputs)
    _note_arbiter_dispatch(target, op, winner.name, tag)
    return out, tag


# --- D3: arbiter dispatch log (did the compiled path win or silently degrade?) --
#
# Every arbitrated dispatch records ``(target, op, selected_candidate | None,
# execution_tag)``. The arbiter *selects* a candidate, but that candidate's
# ``run`` may still decline to the numpy reference at execution time (a device
# error, an unsupported shape) — a **silent degrade** the tag reveals: the
# selection is non-None but the tag is a reference tag. This is the observability
# the plan's D3 asks for, generalized across every backend the arbiter serves
# (the analog of ``runtime.dispatch_fallback_log`` for the arbiter layer).

_ARBITER_LOG: "deque[tuple[str, str, str | None, str]]" = deque(maxlen=4096)


def _note_arbiter_dispatch(target: str, op: str, selected: str | None,
                           tag: str) -> None:
    _ARBITER_LOG.append((target, op, selected, tag))


def arbiter_dispatch_log() -> list[tuple[str, str, str | None, str]]:
    """The ``(target, op, selected, tag)`` of each arbitrated dispatch this process
    (most recent 4096). A ``selected`` that ran but whose ``tag`` is a reference
    tag is a silent degrade."""
    return list(_ARBITER_LOG)


def reset_arbiter_dispatch_log() -> None:
    _ARBITER_LOG.clear()


def arbiter_dispatch_histogram(target: str | None = None, op: str | None = None
                               ) -> dict[tuple[str, str], dict[str, int]]:
    """Per ``(target, op)`` counts of ``{won, degraded, no_candidate}`` — did the
    compiled path win, silently degrade to the reference, or was no candidate
    available? Optionally filtered to a ``target`` / ``op``."""
    from tessera.compiler.emit.kernel_emitter import REFERENCE_EXECUTIONS
    hist: dict[tuple[str, str], dict[str, int]] = {}
    for (t, o, selected, tag) in _ARBITER_LOG:
        if target is not None and t != target:
            continue
        if op is not None and o != op:
            continue
        bucket = hist.setdefault((t, o), {"won": 0, "degraded": 0, "no_candidate": 0})
        if selected is None:
            bucket["no_candidate"] += 1
        elif tag in REFERENCE_EXECUTIONS:
            bucket["degraded"] += 1
        else:
            bucket["won"] += 1
    return hist
