//===- tessera-new/main.cpp — Scaffold a new Tessera project ---------------===//
//
// tessera-new creates a ready-to-build project directory with:
//   - A graph IR skeleton (.mlir)
//   - A Python entry-point that uses tessera.jit
//   - A CMakeLists.txt wired to tessera-compile
//   - A pyproject.toml / requirements stub
//   - A Makefile with `make compile`, `make profile`, `make tune` targets
//
// Example usage:
//   tessera-new my_gemm --template=gemm
//   tessera-new my_attn --template=flash_attn --platform=cuda --arch=sm_90
//   tessera-new my_conv --template=conv2d --dry-run
//
//===----------------------------------------------------------------------===//

#include <iostream>
#include <string>
#include <vector>
#include "common/manifest.hpp"
#include "common/args.hpp"

static const char* TOOL = "tessera-new";

// ---------------------------------------------------------------------------
// File templates
// ---------------------------------------------------------------------------

static std::string mlir_template(const std::string& name,
                                  const std::string& tmpl) {
  if (tmpl == "flash_attn") {
    return "// " + name + " — Tessera Flash-Attention Graph IR\n"
           "// Generated by tessera-new " TESSERA_CLI_VERSION "\n\n"
           "module @" + name + " {\n"
           "  func.func @flash_attn_fwd(\n"
           "      %q: tensor<?x?x?x?xbf16>,\n"
           "      %k: tensor<?x?x?x?xbf16>,\n"
           "      %v: tensor<?x?x?x?xbf16>)\n"
           "      -> tensor<?x?x?x?xbf16> {\n"
           "    %out = \"tessera.flash_attn\"(%q, %k, %v) {\n"
           "        causal = true,\n"
           "        head_dim = 64 : i64\n"
           "    } : (tensor<?x?x?x?xbf16>, tensor<?x?x?x?xbf16>,\n"
           "         tensor<?x?x?x?xbf16>) -> tensor<?x?x?x?xbf16>\n"
           "    return %out : tensor<?x?x?x?xbf16>\n"
           "  }\n"
           "}\n";
  }
  if (tmpl == "conv2d") {
    return "// " + name + " — Tessera Conv2D Graph IR\n"
           "// Generated by tessera-new " TESSERA_CLI_VERSION "\n\n"
           "module @" + name + " {\n"
           "  func.func @conv2d_fwd(\n"
           "      %input: tensor<?x?x?x?xbf16>,\n"
           "      %weight: tensor<?x?x?x?xbf16>)\n"
           "      -> tensor<?x?x?x?xbf16> {\n"
           "    %out = \"tessera.conv2d\"(%input, %weight) {\n"
           "        stride = [1, 1],\n"
           "        padding = [1, 1]\n"
           "    } : (tensor<?x?x?x?xbf16>, tensor<?x?x?x?xbf16>)\n"
           "      -> tensor<?x?x?x?xbf16>\n"
           "    return %out : tensor<?x?x?x?xbf16>\n"
           "  }\n"
           "}\n";
  }
  // Default: GEMM
  return "// " + name + " — Tessera GEMM Graph IR\n"
         "// Generated by tessera-new " TESSERA_CLI_VERSION "\n\n"
         "module @" + name + " {\n"
         "  func.func @matmul(\n"
         "      %a: tensor<?x?xbf16>,\n"
         "      %b: tensor<?x?xbf16>)\n"
         "      -> tensor<?x?xbf16> {\n"
         "    %c = \"tessera.matmul\"(%a, %b) : (\n"
         "        tensor<?x?xbf16>, tensor<?x?xbf16>) -> tensor<?x?xbf16>\n"
         "    return %c : tensor<?x?xbf16>\n"
         "  }\n"
         "}\n";
}

static std::string python_template(const std::string& name,
                                    const std::string& tmpl,
                                    const std::string& platform) {
  std::string s = "\"\"\"" + name + " — Tessera " + tmpl +
                  " kernel (generated by tessera-new " TESSERA_CLI_VERSION ")\"\"\"\n\n"
                  "import tessera\n"
                  "import numpy as np\n\n";

  if (tmpl == "flash_attn") {
    s += "@tessera.jit(target=\"" + platform + "\")\n"
         "def flash_attn_fwd(Q, K, V):\n"
         "    \"\"\"Causal flash-attention forward pass.\"\"\"\n"
         "    return tessera.ops.flash_attn(Q, K, V, causal=True)\n\n"
         "if __name__ == \"__main__\":\n"
         "    B, H, S, D = 2, 8, 512, 64\n"
         "    Q = np.random.randn(B, H, S, D).astype(np.float16)\n"
         "    K = np.random.randn(B, H, S, D).astype(np.float16)\n"
         "    V = np.random.randn(B, H, S, D).astype(np.float16)\n"
         "    out = flash_attn_fwd(Q, K, V)\n"
         "    print(f\"output shape: {out.shape}\")\n";
  } else if (tmpl == "conv2d") {
    s += "@tessera.jit(target=\"" + platform + "\")\n"
         "def conv2d_fwd(x, w):\n"
         "    \"\"\"Conv2D forward pass.\"\"\"\n"
         "    return tessera.ops.conv2d(x, w, stride=1, padding=1)\n\n"
         "if __name__ == \"__main__\":\n"
         "    x = np.random.randn(1, 64, 56, 56).astype(np.float16)\n"
         "    w = np.random.randn(64, 64, 3, 3).astype(np.float16)\n"
         "    out = conv2d_fwd(x, w)\n"
         "    print(f\"output shape: {out.shape}\")\n";
  } else {
    s += "@tessera.jit(target=\"" + platform + "\")\n"
         "def matmul(A, B):\n"
         "    \"\"\"General matrix multiplication.\"\"\"\n"
         "    return tessera.ops.gemm(A, B)\n\n"
         "if __name__ == \"__main__\":\n"
         "    M, N, K = 2048, 2048, 2048\n"
         "    A = np.random.randn(M, K).astype(np.float16)\n"
         "    B = np.random.randn(K, N).astype(np.float16)\n"
         "    C = matmul(A, B)\n"
         "    print(f\"output shape: {C.shape}\")\n";
  }
  return s;
}

static std::string makefile_template(const std::string& name,
                                      const std::string& platform,
                                      const std::string& arch) {
  return "# Tessera project Makefile — generated by tessera-new " TESSERA_CLI_VERSION "\n\n"
         "NAME     := " + name + "\n"
         "PLATFORM := " + platform + "\n"
         "ARCH     := " + arch + "\n"
         "OUT      := build/\n\n"
         ".PHONY: all compile opt profile run tune inspect clean\n\n"
         "all: compile\n\n"
         "opt:\n"
         "\ttessera-opt $(NAME).mlir --alias=graph-to-schedule --verify \\\n"
         "\t    --out-dir $(OUT) -o $(OUT)/ir/schedule.mlir\n\n"
         "compile:\n"
         "\ttessera-compile $(NAME).mlir \\\n"
         "\t    --platform=$(PLATFORM) --arch=$(ARCH) \\\n"
         "\t    --to=ptx --enable-tensor-cores --emit-host \\\n"
         "\t    --out-dir $(OUT)\n\n"
         "profile:\n"
         "\ttessera-profiler $(OUT) --peak-tflops=989 --peak-bw=3350\n\n"
         "run:\n"
         "\ttessera-run $(OUT) --rtol=1e-3 --atol=1e-5\n\n"
         "tune:\n"
         "\ttessera-autotune $(NAME).mlir --searcher=random --trials=64 \\\n"
         "\t    --platform=$(PLATFORM) --arch=$(ARCH) --out-dir $(OUT)\n\n"
         "inspect:\n"
         "\ttessera-inspect $(OUT) --format=md\n\n"
         "clean:\n"
         "\trm -rf $(OUT)\n";
}

static std::string cmake_template(const std::string& name,
                                   const std::string& platform,
                                   const std::string& arch) {
  return "cmake_minimum_required(VERSION 3.20)\n"
         "project(" + name + " LANGUAGES CXX)\n\n"
         "# Tessera compile step\n"
         "add_custom_command(\n"
         "  OUTPUT  ${CMAKE_BINARY_DIR}/kernels/demo.ptx\n"
         "  COMMAND tessera-compile ${CMAKE_CURRENT_SOURCE_DIR}/" + name + ".mlir\n"
         "          --platform=" + platform + " --arch=" + arch + " --to=ptx\n"
         "          --enable-tensor-cores --emit-host\n"
         "          --out-dir ${CMAKE_BINARY_DIR}\n"
         "  DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/" + name + ".mlir\n"
         "  COMMENT \"Compiling Tessera IR for " + arch + "\"\n"
         ")\n"
         "add_custom_target(" + name + "_kernels ALL\n"
         "  DEPENDS ${CMAKE_BINARY_DIR}/kernels/demo.ptx\n"
         ")\n";
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
int main(int argc, char** argv) {
  std::string opt_template, opt_platform, opt_arch;
  std::vector<std::string> inputs;  // first positional = project name

  tessera::Args args(TOOL, "Scaffold a new Tessera kernel project", argc, argv);
  args.option("--template", "Project template {gemm,flash_attn,conv2d}", &opt_template, "gemm")
      .option("--platform", "Target platform {cuda,hip,cpu}",            &opt_platform, "cuda")
      .option("--arch",     "Target arch (sm_90, gfx1100, avx2, ...)",   &opt_arch, "sm_90")
      .positional("name",   "Project name (becomes directory name)",      &inputs);

  if (!args.parse()) return args.exit_code();

  if (inputs.empty()) {
    TLOG_ERROR(TOOL, "project name is required");
    TLOG_INFO(TOOL,  "usage: tessera-new <name> [--template=gemm]");
    return tessera::EXIT_PARSE_ERROR;
  }

  std::string name = inputs[0];
  // Sanitize name: only allow [a-zA-Z0-9_-]
  for (char c : name) {
    if (!std::isalnum(c) && c != '_' && c != '-') {
      TLOG_ERROR(TOOL, "project name '" + name +
                 "' contains invalid character '" + std::string(1, c) + "'");
      return tessera::EXIT_PARSE_ERROR;
    }
  }

  if (opt_template != "gemm" && opt_template != "flash_attn" &&
      opt_template != "conv2d") {
    TLOG_ERROR(TOOL, "unknown template '" + opt_template +
               "'; expected gemm, flash_attn, or conv2d");
    return tessera::EXIT_PARSE_ERROR;
  }

  std::string project_dir = name;
  int rc = tessera::EXIT_OK;

  try {
    if (args.dry_run()) {
      TLOG_INFO(TOOL, "[dry-run] would create project: " + project_dir + "/");
      TLOG_INFO(TOOL, "  " + project_dir + "/" + name + ".mlir");
      TLOG_INFO(TOOL, "  " + project_dir + "/" + name + ".py");
      TLOG_INFO(TOOL, "  " + project_dir + "/Makefile");
      TLOG_INFO(TOOL, "  " + project_dir + "/CMakeLists.txt");
    } else {
      // Create directory
      tessera::ensureDir(project_dir);

      // Write files
      writeFile(project_dir + "/" + name + ".mlir",
                mlir_template(name, opt_template));
      writeFile(project_dir + "/" + name + ".py",
                python_template(name, opt_template, opt_platform));
      writeFile(project_dir + "/Makefile",
                makefile_template(name, opt_platform, opt_arch));
      writeFile(project_dir + "/CMakeLists.txt",
                cmake_template(name, opt_platform, opt_arch));

      std::cerr << "[" << TOOL << "] created project '" << name << "'/\n"
                << "  " << name << ".mlir   — Graph IR skeleton\n"
                << "  " << name << ".py     — Python entry-point\n"
                << "  Makefile             — compile / profile / tune targets\n"
                << "  CMakeLists.txt       — CMake integration\n\n"
                << "Next steps:\n"
                << "  cd " << name << " && make compile\n"
                << "  make profile\n"
                << "  make tune\n";
    }
  } catch (const std::exception& e) {
    TLOG_ERROR(TOOL, e.what());
    tessera::json_result(TOOL, project_dir, false,
                         "\"error\":\"" + tessera::jsonEscape(e.what()) + "\"");
    return tessera::EXIT_IO_ERROR;
  }

  tessera::json_result(TOOL, project_dir, true,
                       "\"name\":\"" + tessera::jsonEscape(name) + "\","
                       "\"template\":\"" + opt_template + "\"");
  return rc;
}
