[project]
name = "tessera_gemma"
version = "0.1.0"
description = "Starter port of Gemma to the Tessera programming model"
requires-python = ">=3.9"
dependencies = ["torch>=2.2", "numpy>=1.23", "einops>=0.7", "sentencepiece>=0.1.99"]
authors = [{name="Tessera PM Port", email="devnull@example.com"}]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
