"""Native NVIDIA plugin execute-and-compare proofs."""

from tests._support import nvidia_plugin_cases as cases


test_live_nvidia_generic_cuda_gated = cases.test_live_nvidia_generic_cuda_gated
test_live_nvidia_arbitrated_residual_executes = cases.test_live_nvidia_arbitrated_residual_executes
test_live_nvidia_tile_matmul_schedule_candidates = cases.test_live_nvidia_tile_matmul_schedule_candidates
test_live_nvidia_emitted_ragged_degrade_is_logged = cases.test_live_nvidia_emitted_ragged_degrade_is_logged
test_live_nvidia_flash_attention = cases.test_live_nvidia_flash_attention
test_live_nvidia_gated_swiglu = cases.test_live_nvidia_gated_swiglu
test_live_nvidia_pointwise_dag = cases.test_live_nvidia_pointwise_dag
test_live_nvidia_pointwise_max_min_preserve_nan = cases.test_live_nvidia_pointwise_max_min_preserve_nan
test_live_nvidia_pointwise_gelu_and_nan_sign = cases.test_live_nvidia_pointwise_gelu_and_nan_sign
test_live_nvidia_mma_fused_tensor_core = cases.test_live_nvidia_mma_fused_tensor_core
test_live_nvidia_mma_attn_tensor_core = cases.test_live_nvidia_mma_attn_tensor_core
test_live_nvidia_mma_attn_large_nk_delegates_to_scalar = cases.test_live_nvidia_mma_attn_large_nk_delegates_to_scalar
test_live_nvidia_mma_attn_large_magnitude_delegates_not_degrades = cases.test_live_nvidia_mma_attn_large_magnitude_delegates_not_degrades
test_live_nvidia_tensor_core_dtype_variants = cases.test_live_nvidia_tensor_core_dtype_variants
test_live_nvidia_tf32_fp8_composed_transformer_lanes = cases.test_live_nvidia_tf32_fp8_composed_transformer_lanes
