trainer:
  model_name: sshleifer/tiny-gpt2
  lr: 1.0e-05
  l1_samples: 2
  l2_samples: 2
  max_new_tokens: 64
  temperature: 0.7
  top_p: 0.95
  clip_range: 0.2
  kl_coeff: 0.01
  seed: 1234
  device: cpu
data:
  path: data/sample_math.jsonl
num_steps: 3
batch_size: 2
