#!/usr/bin/env python3
"""Stub / completeness surface report (compiler-testing program, item #1).

Reads the existing generated audit dashboards (the count/status truth per
Decision #26) and emits a single ranked rollup of the *software-actionable*
completeness gaps — separating them from the hardware-gated rows that are
expected and honestly cataloged.

The point is a prioritized worklist, not a new source of truth: every number
here is derived from the checked-in CSVs, so this is rerunnable and never drifts.

    python3 scripts/stub_surface_report.py            # print
    python3 scripts/stub_surface_report.py --write    # write docs/audit/generated/stub_surface.md
"""

from __future__ import annotations

import argparse
import collections
import csv
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
GEN = ROOT / "docs" / "audit" / "generated"
AUDIT = ROOT / "docs" / "audit"

# op×target proof-ladder gates that are *software*-actionable vs hardware-gated.
_SOFTWARE_GATES = {"graph_ir", "schedule", "tile", "codegen", "numerical"}
_HARDWARE_GATES = {"hardware_smoke", "toolchain", "link"}


def _read(path: pathlib.Path) -> list[dict]:
    return list(csv.DictReader(path.open())) if path.exists() else []


def _find(name: str) -> pathlib.Path | None:
    for base in (GEN, AUDIT):
        p = base / name
        if p.exists():
            return p
    hits = list(AUDIT.rglob(name))
    return hits[0] if hits else None


def build_report() -> str:
    out: list[str] = []
    w = out.append
    w("# Stub / completeness surface — software-actionable worklist")
    w("")
    w("> Generated by `scripts/stub_surface_report.py` from the checked-in audit")
    w("> dashboards. Hardware-gated rows (NVIDIA/ROCm/TPU/... needing real silicon)")
    w("> are separated out — they are expected-incomplete, not stubs. **Rerun to")
    w("> refresh; do not hand-edit.**")
    w("")

    # ── 1. Verifier stubs ────────────────────────────────────────────────────
    vc = _read(GEN / "verifier_coverage.csv")
    by = collections.Counter(r["impl_status"] for r in vc)
    stub = [r for r in vc if r["impl_status"] == "trivial_stub"]
    noverif = [r for r in vc if r["impl_status"] == "no_verifier"]
    w("## P0 — verifier stubs (verify() declared but no-ops)")
    w("")
    w(f"ODS ops: **{by.get('real',0)} real**, "
      f"**{len(stub)} trivial_stub**, **{len(noverif)} no_verifier**, "
      f"{by.get('absent',0)} absent.")
    w("")
    w(f"**{len(stub)} trivial-stub verifiers (definite stubs — close these):**")
    for r in sorted(stub, key=lambda r: r["op_class"]):
        w(f"  - `{r['op_class']}` ({r['td_file'].split('/')[-1]})")
    w("")
    w(f"_{len(noverif)} no-verifier ops need manual triage_ (many — pure "
      "elementwise — legitimately need none; control/collective/reshape-shaped "
      "ops should get one). Representative:")
    w("  " + ", ".join(f"`{r['op_class']}`" for r in noverif[:12]) + ", …")
    w("")

    # ── 2. Software conformance gaps (proof ladder) ──────────────────────────
    cf = _read(_find("op_target_conformance.csv") or pathlib.Path("x"))
    w("## P1 — software conformance gaps (op×target proof ladder)")
    w("")
    if cf:
        overall = collections.Counter(r["overall"] for r in cf)
        gate = collections.Counter(r.get("first_failing_gate", "") for r in cf
                                   if r.get("first_failing_gate"))
        sw = [r for r in cf
              if r.get("first_failing_gate") in _SOFTWARE_GATES]
        hw = [r for r in cf
              if r.get("first_failing_gate") in _HARDWARE_GATES]
        w(f"{len(cf)} op×target cells: {dict(overall)}.")
        w("")
        w(f"First-failing gate: {dict(gate)}.")
        w("")
        w(f"**Software-actionable ({len(sw)}** stop at "
          f"{sorted(_SOFTWARE_GATES & set(gate))}**) — real lowering/codegen "
          "gaps to fix:**")
        for r in sw:
            w(f"  - `{r['op']}` → `{r['target']}` (stops @ "
              f"{r['first_failing_gate']})")
        w("")
        w(f"_Hardware-gated ({len(hw)} stop at "
          f"{sorted(_HARDWARE_GATES & set(gate))}) — expected; need real "
          "silicon, not code._")
    else:
        w("_(op_target_conformance.csv not found)_")
    w("")

    # ── 3. Thin-test tail (the differential-generator target) ────────────────
    tc = _read(GEN / "test_coverage.csv")
    w("## P2 — thin-test tail (the differential-generator target, item #2)")
    w("")
    if tc:
        buckets = collections.Counter(r["bucket"] for r in tc)
        zero = [r for r in tc if int(r["total_refs"]) == 0]
        needs = [r for r in tc if r["bucket"] == "needs_direct_test"]
        w(f"{len(tc)} ops: {dict(buckets)}.")
        w("")
        w(f"**{len(needs)} `needs_direct_test`** + **{len(zero)} zero-ref** ops "
          "— the long tail a generative differential harness (tracer vs numpy) "
          "covers far more cheaply than hand-written tests.")
        w("")
        w("Zero-ref sample: "
          + ", ".join(f"`{r['op']}`" for r in zero[:20]) + ", …")
    else:
        w("_(test_coverage.csv not found)_")
    w("")

    # ── Summary ──────────────────────────────────────────────────────────────
    w("## Takeaway")
    w("")
    w("- The compiler is **not stub-riddled**: the actionable surface is the "
      "trivial-stub verifiers + a handful of software conformance cells; "
      "everything else is hardware-gated (honest) or thin-test (generative).")
    w("- **#4 (IR round-trip + fuzz)** hardens the parser/printer/verifier "
      "across all ops cheaply, no oracle needed.")
    w("- **#2 (differential generator)** is the right tool for the "
      f"~{len([r for r in tc if r['bucket']=='needs_direct_test']) if tc else '?'} "
      "needs-direct-test ops + miscompile detection.")
    w("")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()
    report = build_report()
    if args.write:
        dest = GEN / "stub_surface.md"
        dest.write_text(report)
        print(f"wrote {dest}")
    else:
        print(report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
