"""Host-free NVIDIA plugin registration and rejection contracts."""

from tests._support import nvidia_plugin_cases as cases


test_nvidia_runner_registered = cases.test_nvidia_runner_registered
test_nvidia_emitter_registered_produces_cuda = cases.test_nvidia_emitter_registered_produces_cuda
test_nvidia_emit_is_deterministic = cases.test_nvidia_emit_is_deterministic
test_nvidia_emitter_rejects_unsupported = cases.test_nvidia_emitter_rejects_unsupported
test_nvidia_c5_candidates_registered_and_emit = cases.test_nvidia_c5_candidates_registered_and_emit
test_nvidia_flash_attn_candidate_registered_and_emits = cases.test_nvidia_flash_attn_candidate_registered_and_emits
test_nvidia_mma_attn_candidate_registered = cases.test_nvidia_mma_attn_candidate_registered
test_nvidia_mma_fused_candidate_registered_and_applies = cases.test_nvidia_mma_fused_candidate_registered_and_applies
test_nvidia_mma_gated_candidates_registered_and_apply_by_storage = cases.test_nvidia_mma_gated_candidates_registered_and_apply_by_storage
test_nvidia_tf32_fp8_composed_candidates_registered_by_storage = cases.test_nvidia_tf32_fp8_composed_candidates_registered_by_storage
test_nvidia_mma_fused_rejects_bad_inputs = cases.test_nvidia_mma_fused_rejects_bad_inputs
test_nvidia_generic_candidate_registered = cases.test_nvidia_generic_candidate_registered
test_nvidia_tile_matmul_schedule_candidates_registered = cases.test_nvidia_tile_matmul_schedule_candidates_registered
test_nvidia_arbitrated_residual_threads_not_raises = cases.test_nvidia_arbitrated_residual_threads_not_raises
test_nvidia_gemm_helpers_reject_mismatched_k = cases.test_nvidia_gemm_helpers_reject_mismatched_k
test_nvidia_matmul_candidates_registered = cases.test_nvidia_matmul_candidates_registered
test_nvidia_matmul_off_gpu_arbitrates_to_reference = cases.test_nvidia_matmul_off_gpu_arbitrates_to_reference
test_nvidia_pointwise_emits_gelu_and_nan_safe_shims = cases.test_nvidia_pointwise_emits_gelu_and_nan_safe_shims
test_nvidia_pointwise_max_min_nan_shims_and_buffer_free = cases.test_nvidia_pointwise_max_min_nan_shims_and_buffer_free


def test_nvidia_missing_required_buffer_declines_not_segfault(
    python_subprocess_env,
):
    """Keep the shared-import-state subprocess contract in the CPU lane."""
    return cases.test_nvidia_missing_required_buffer_declines_not_segfault(
        python_subprocess_env
    )
