"""Audit-D (2026-05-22) — drift gate for the test-coverage-by-op audit.

The ``primitive_coverage.py`` registry marks all 432 entries as
``tests=complete``.  That's a category-level rollup, not a per-op
proof.  This gate sits on top of
``python/tessera/compiler/test_coverage_audit.py`` and pins the
plausible numbers so we notice when:

  * A sweep accidentally deletes a chunk of tests (total floors).
  * A sentinel high-traffic op (matmul / flash_attn / softmax / gemm)
    silently loses coverage during a rewrite.
  * The generated by-op section in
    ``docs/audit/generated/test_coverage.md`` drifts out of sync
    with the live scan.

Honest scope note matches the module's: reference counts are not
the same as numerical-coverage quality.  The floors here are loose
on purpose — they catch regressions, not normal week-to-week churn.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tessera.compiler.test_coverage_audit import (
    OpTestCoverage,
    collect_op_test_coverage,
    coverage_summary,
    render_dashboard,
    thinly_tested_ops,
    top_tested_ops,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
# The per-op coverage table + classification triage were merged
# (2026-06-04) into one generated doc managed by the generated-doc
# registry; the by-op section is rendered first, so these content
# assertions still hold against the merged doc.
DASHBOARD = REPO_ROOT / "docs" / "audit" / "generated" / "test_coverage.md"


# ─────────────────────────────────────────────────────────────────────────
# Headline floors
# ─────────────────────────────────────────────────────────────────────────


def test_total_op_count_floor() -> None:
    """The registry currently has 432 ops; floor at 400 to absorb the
    rare deletion but flag accidental large drops."""
    rows = collect_op_test_coverage()
    assert len(rows) >= 400, (
        f"Op count dropped below 400 (got {len(rows)}).  "
        f"Did the registry get partially cleared?"
    )


def test_total_reference_count_floor() -> None:
    """Locked at the Audit-D-2 landing.  Total Python + lit refs is
    ~1,650 with the vectorized scanner (which counts each location
    once instead of once-per-pattern).  Floor at 1,300 absorbs
    ordinary churn but flags a sweep that accidentally deletes
    whole test files."""
    summary = coverage_summary()
    total = summary["total_python_refs"] + summary["total_lit_refs"]
    assert total >= 1300, (
        f"Total test references across all ops dropped below 1,300 "
        f"(got {total} = {summary['total_python_refs']} py + "
        f"{summary['total_lit_refs']} lit).  Did a test sweep get "
        f"deleted by accident?"
    )


def test_well_tested_op_count_floor() -> None:
    """At Audit-D-2 landing, 24 ops have ≥10 references (vectorized
    scanner — was 41 with the older over-counting scanner).  Floor
    at 18 catches loss of any major heavy hitter."""
    summary = coverage_summary()
    assert summary["well_tested"] >= 18, (
        f"Well-tested op count (≥10 refs) dropped below 18 "
        f"(got {summary['well_tested']})."
    )


def test_ops_with_negative_tests_floor() -> None:
    """At Audit-D landing, 37 ops have at least one nearby
    `pytest.raises`.  Floor at 25 — negative-path coverage is the
    most valuable kind, so a regression here is worth flagging."""
    summary = coverage_summary()
    assert summary["with_negative_tests"] >= 25, (
        f"Ops with negative-test coverage dropped below 25 "
        f"(got {summary['with_negative_tests']}).  Did we lose a "
        f"`pytest.raises` block during a refactor?"
    )


# ─────────────────────────────────────────────────────────────────────────
# Sentinel ops — high-traffic primitives that must NOT silently
# lose coverage.
# ─────────────────────────────────────────────────────────────────────────


# (op_name, minimum_total_refs).  Floors are set to roughly half the
# current count — they catch real regressions while absorbing ordinary
# churn.  Counts are from the vectorized scanner (each match location
# counted exactly once).
_SENTINEL_OP_FLOORS = (
    ("matmul",     150),    # currently 302
    ("flash_attn",  50),    # currently  99
    ("gemm",        35),    # currently  71
    ("softmax",     40),    # currently  81
    ("reduce",      30),    # currently  64
    ("mul",         25),    # currently  53
    ("add",         18),    # currently  36
    ("relu",        15),    # currently  31
    ("dropout",     10),    # currently  22
    ("gelu",        12),    # currently  26
    ("rope",        10),    # currently  24
    ("transpose",   12),    # currently  25
    ("layer_norm",   8),    # currently  19
    ("cast",        12),    # currently  26
)


@pytest.mark.parametrize(
    "op_name,floor", _SENTINEL_OP_FLOORS, ids=[s[0] for s in _SENTINEL_OP_FLOORS]
)
def test_sentinel_op_reference_count_floor(op_name: str, floor: int) -> None:
    """High-traffic ops must retain at least ~half their current
    test coverage.  A drop below floor means a major test file
    got accidentally truncated or renamed."""
    rows = {r.op_name: r for r in collect_op_test_coverage()}
    cov = rows.get(op_name)
    assert cov is not None, (
        f"Sentinel op {op_name!r} is missing from primitive_coverage.py.  "
        f"Was the registry refactored?"
    )
    assert cov.total_refs >= floor, (
        f"Sentinel op {op_name!r} test references dropped below floor "
        f"{floor} (got {cov.total_refs} = {cov.python_refs} py + "
        f"{cov.lit_refs} lit).  Investigate whether a test file was "
        f"deleted or renamed."
    )


# ─────────────────────────────────────────────────────────────────────────
# Matmul / flash_attn — the two flagship ops — must keep their
# negative-test coverage.
# ─────────────────────────────────────────────────────────────────────────


def test_matmul_has_negative_tests() -> None:
    rows = {r.op_name: r for r in collect_op_test_coverage()}
    matmul = rows["matmul"]
    assert matmul.negative_refs >= 4, (
        f"matmul lost negative-test coverage (got "
        f"{matmul.negative_refs} pytest.raises near references; "
        f"baseline 9)."
    )


def test_gemm_has_negative_tests() -> None:
    rows = {r.op_name: r for r in collect_op_test_coverage()}
    gemm = rows["gemm"]
    assert gemm.negative_refs >= 3, (
        f"gemm lost negative-test coverage (got {gemm.negative_refs} "
        f"pytest.raises near references; baseline 6)."
    )


# ─────────────────────────────────────────────────────────────────────────
# Thin-coverage envelope — the thinly-tested set should NOT explode.
# ─────────────────────────────────────────────────────────────────────────


def test_thinly_tested_count_does_not_balloon() -> None:
    """At Audit-D-2 landing, ~291/432 ops have ≤1 reference under
    the vectorized scanner.  Many are legitimate (alias rollups, S15
    data combinators tested elsewhere, optimizer / schedule helpers
    under conformance smoke tests, etc.) — the classification
    classification section in ``test_coverage.md`` triages the buckets.
    Cap at 350 — going above that means we've added a wave of
    unexposed primitives without writing tests OR without a
    classification rule landing."""
    summary = coverage_summary()
    assert summary["thinly_tested"] <= 350, (
        f"Thinly-tested op count rose above 350 "
        f"(got {summary['thinly_tested']}).  A wave of unexposed "
        f"primitives was added without tests."
    )


# ─────────────────────────────────────────────────────────────────────────
# Top-20 invariant
# ─────────────────────────────────────────────────────────────────────────


def test_matmul_is_the_most_tested_op() -> None:
    """matmul is the universal proof anchor across CPU/GPU/lit suites.
    If anything else ever leads the leaderboard, investigate — that's
    not a regression, but it does mean the testing surface shifted
    significantly."""
    top = top_tested_ops(1)
    assert top[0].op_name == "matmul", (
        f"Top-tested op is {top[0].op_name!r}, not 'matmul' "
        f"(refs={top[0].total_refs}).  This is unusual — verify the "
        f"matmul test suite is intact."
    )


# ─────────────────────────────────────────────────────────────────────────
# Dashboard drift gate
# ─────────────────────────────────────────────────────────────────────────


def test_dashboard_exists() -> None:
    assert DASHBOARD.exists(), (
        f"Generated dashboard missing: "
        f"{DASHBOARD.relative_to(REPO_ROOT)}.  Regenerate via "
        f"`tessera.compiler.test_coverage_audit.write_dashboard()`."
    )


def test_dashboard_pins_canonical_phrases() -> None:
    """The dashboard structure (headings) is part of the contract —
    consumers (and future docs) link into these sections."""
    if not DASHBOARD.exists():
        pytest.skip("dashboard not generated yet")
    text = DASHBOARD.read_text()
    for phrase in (
        "# Test Coverage by Op Family",
        "## Headline",
        "## Top 20 most-tested ops",
        "## Thinly-tested ops",
        "Honest scope note",
    ):
        assert phrase in text, (
            f"Test-coverage dashboard missing canonical phrase {phrase!r}"
        )


def test_dashboard_includes_matmul_sentinel() -> None:
    """The top section must mention matmul — it's the single most
    visible op in the audit and its omission means the renderer
    broke."""
    if not DASHBOARD.exists():
        pytest.skip("dashboard not generated yet")
    text = DASHBOARD.read_text()
    assert "`matmul`" in text, (
        "Dashboard rendered without the matmul row — top-20 table broke."
    )


def test_dashboard_headline_numbers_match_live_scan() -> None:
    """The on-disk dashboard's headline numbers should match the
    live scan within reasonable tolerance (allowing for the rare
    case where a developer adds a test but hasn't regenerated the
    dashboard yet)."""
    if not DASHBOARD.exists():
        pytest.skip("dashboard not generated yet")
    text = DASHBOARD.read_text()
    summary = coverage_summary()
    # The total ops number is the most stable — it changes only when
    # the registry changes.  Require it to be in the dashboard.
    assert f"**{summary['total_ops']}** ops" in text, (
        f"Dashboard headline ops count is stale.  Live scan says "
        f"{summary['total_ops']} ops; regenerate via "
        f"`tessera.compiler.test_coverage_audit.write_dashboard()`."
    )


# ─────────────────────────────────────────────────────────────────────────
# Import-binding scanner (PR #568 review follow-up)
# ─────────────────────────────────────────────────────────────────────────
#
# The scanner used to see only single-line ``from tessera.<mod> import X``
# and only registry-spelled names.  That silently scored zero for any op
# whose suite used the parenthesized multi-line import form, or whose
# module exports a short name for a prefixed registry op — which is how
# `tridiagonal_solve` and the whole coalition-lattice family landed in
# PR #568 classified `structural_only` despite having dedicated suites.


def _synthetic_dotted_call(module: str, op: str) -> tuple[str, str]:
    """Build ``module.op`` and ``tessera.module.op`` sample text.

    Same rationale as ``_synthetic_import``: writing the literal dotted
    form directly in this file — module name, then a dot, then an op
    name, adjacent in the source text — would BE a real reference as far
    as the scanner is concerned, since it reads this file's raw bytes
    like any other file under ``tests/unit/``.  (Note: even this
    docstring has to describe the shape rather than show one — spelling
    an example out is exactly the mistake this helper exists to avoid.)
    Callers must pass ``module``/``op`` as separate arguments (as done
    here) so the joined form only ever exists at runtime, never in the
    source.
    """
    return f"{module}.{op}", f"tessera.{module}.{op}"


def _synthetic_import(module: str, name: str) -> str:
    """Build a sample import line WITHOUT writing it as a literal.

    This file is itself inside ``tests/unit/``, which is the tree the
    coverage scanner walks.  A literal ``from tessera.<mod> import <op>``
    in a fixture would be indistinguishable from a real reference and
    would silently inflate that op's row in the live dashboard — which
    the generated-doc drift gate then bakes in.  Assembling the string
    at runtime keeps the fixtures out of the scan.
    """
    return f"from tessera.{module} import {name}"


def _refs(op_name: str) -> int:
    rows = {r.op_name: r for r in collect_op_test_coverage()}
    assert op_name in rows, f"{op_name} is not in the primitive registry"
    return rows[op_name].total_refs


def test_family_module_import_is_seen_single_line() -> None:
    """A single-line family-module import of the solver counts.

    Regression pin for the PR #568 review finding: the solver suite
    exists (`tests/unit/test_tridiagonal_solve.py`) and must not read
    as an untested op.

    (The import form is deliberately described rather than quoted —
    see `_synthetic_import` for why a literal here would corrupt the
    very number this test is pinning.)
    """
    assert _refs("tridiagonal_solve") >= 2, (
        "tridiagonal_solve scores as untested — `solvers_ops` fell out of "
        "_FAMILY_MODULES, or the import-binding scan regressed."
    )


def test_multiline_import_and_prefixed_family_are_seen() -> None:
    """Parenthesized imports + ``game_``-prefixed registry names.

    ``tessera.game`` exports ``subset_zeta``; the registry names it
    ``game_subset_zeta``.  Both halves must work or the family scores
    zero across the board.
    """
    for op in ("game_subset_zeta", "game_mex", "game_boltzmann_value"):
        assert _refs(op) >= 2, (
            f"{op} scores as untested — multi-line import parsing or the "
            f"_MODULE_PREFIXED_FAMILIES mapping regressed."
        )


def test_repeated_local_imports_do_not_multiply_call_sites() -> None:
    """Call sites are counted once per bound name, not once per import.

    ``test_game_lattice.py`` re-imports ``boltzmann_value`` inside
    several test bodies.  A per-import full-text rescan multiplied its
    call sites ~3.5x, which would inflate the audit rather than fix it.
    """
    from tessera.compiler import test_coverage_audit as tca

    # Synthetic source is ASSEMBLED, never written as a literal: this
    # file lives in tests/unit/, which is exactly what the scanner walks,
    # so an inline ``from tessera.game import ...`` line here would be
    # counted as a real reference and inflate the live dashboard.
    imp = _synthetic_import("game", "boltzmann_value")
    text = (
        f"{imp}\n"
        "def a():\n"
        f"    {imp}\n"
        "    return boltzmann_value(1)\n"
        "def b():\n"
        f"    {imp}\n"
        "    return boltzmann_value(2)\n"
    )
    registry = frozenset({"game_boltzmann_value"})
    offsets = tca._import_binding_refs(text, registry)["game_boltzmann_value"]
    # 3 imports + 2 distinct call sites, each counted exactly once.
    assert len(offsets) == len(set(offsets)) == 5, (
        f"expected 3 imports + 2 unique call sites = 5, got {len(offsets)} "
        f"({len(set(offsets))} unique) — call-site dedupe regressed"
    )


def test_dotted_calls_are_not_double_counted() -> None:
    """``mod.op(...)`` belongs to the combined regex, not the binding scan."""
    from tessera.compiler import test_coverage_audit as tca

    op = "tridiagonal" + "_solve"          # see _synthetic_import's note
    text = (
        f"{_synthetic_import('solvers_ops', op)}\n"
        f"solvers_ops.{op}(a)\n"
    )
    registry = frozenset({op})
    offsets = tca._import_binding_refs(text, registry)[op]
    assert len(offsets) == 1, (
        f"the dotted call was double-counted by the binding scan: {offsets}"
    )


def test_dotted_call_into_prefixed_family_resolves_to_registry_name() -> None:
    """A dotted call into a module-prefixed family — both the short
    form and the fully-qualified form — resolves to the registry name.

    Regression pin for a PR #569 review finding: the combined-regex path
    (dotted calls, as opposed to imports) captured the module's short
    name with no knowledge of ``_MODULE_PREFIXED_FAMILIES``, so a suite
    written in the dotted-call style would score zero for every
    ``game_*`` op despite real references — exactly the failure mode
    this whole scanner rewrite exists to fix.

    (No dotted form is written as a literal anywhere in this test file —
    see ``_synthetic_dotted_call``.)
    """
    from tessera.compiler import test_coverage_audit as tca

    short, qualified = _synthetic_dotted_call("game", "subset_zeta")
    registry = frozenset({"game_subset_zeta"})
    text = f"import tessera.game as game\nx = {short}(v)\ny = {qualified}(w)\n"
    resolved = [
        tca._resolve_py_match(m, registry)
        for m in tca._PY_OP_REFERENCE_RE.finditer(text)
    ]
    assert resolved == ["game_subset_zeta", "game_subset_zeta"], (
        f"dotted calls into a prefixed family did not resolve to the "
        f"registry name: {resolved}"
    )


def test_dotted_call_into_prefixed_family_ignores_non_op_names() -> None:
    """A dotted call to a non-op helper in a prefixed family must not
    fabricate a bogus registry key — a helper name that isn't itself
    registered (prefixed or not) must resolve to nothing."""
    from tessera.compiler import test_coverage_audit as tca

    short, _qualified = _synthetic_dotted_call("game", "lattice_players")
    registry = frozenset({"game_subset_zeta"})  # lattice_players NOT registered
    text = f"{short}(n)\n"
    matches = [
        tca._resolve_py_match(m, registry)
        for m in tca._PY_OP_REFERENCE_RE.finditer(text)
    ]
    assert matches == [None], f"expected the unregistered helper to be dropped, got {matches}"


def test_dotted_call_into_non_prefixed_family_is_unaffected() -> None:
    """A family module NOT in ``_MODULE_PREFIXED_FAMILIES`` must resolve
    a dotted call unchanged, straight to its own name."""
    from tessera.compiler import test_coverage_audit as tca

    short, _qualified = _synthetic_dotted_call("optim", "sgd")
    registry = frozenset({"sgd"})
    text = f"{short}(params, lr)\n"
    matches = [
        tca._resolve_py_match(m, registry)
        for m in tca._PY_OP_REFERENCE_RE.finditer(text)
    ]
    assert matches == ["sgd"]
